Repository kyma-project/community, pull requests merged in 2018-10, with the labels that each got.

#86 Add a section about related components to the CR template
  guidelines/templates/resources/custom-resource.md
Labels: area/documentation, enhancement

#90 Update custom-resource.md
  guidelines/templates/resources/custom-resource.md
Labels: area/documentation, bug

#97 Prow WG - update leaders and meeting's recording link
  sig-and-wg/wg-prow/README.md
Labels: area/ci, wg/prow

#87 Enable external links validation on PRs
  governance.Jenkinsfile
Labels: WIP, area/ci, area/documentation, enhancement

#99 Adjust CRD guideline to use kyma-project.io domain
  guidelines/custom-resource-definitions.md
Labels: area/community, bug

#100 Update the chart_README.md template
  guidelines/templates/resources/chart_README.md
Labels: area/community, area/documentation

#95 Update issue workflow with custom label "decision"
  issues-workflow.md
Labels: area/community, area/documentation

#102 Prepare a template for Getting Started document
  guidelines/content-guidelines/content-strategy.md
  guidelines/templates/README.md
  guidelines/templates/resources/getting-started.md
Labels: area/documentation

#101 Update the guidelines to include information on obligatory labels in PRs
  CONTRIBUTING.md
  git-workflow.md
Labels: area/community, area/documentation

#111 Add aerfio to CODEOWNERS
  CODEOWNERS
Labels: area/community

#113 Disable external links validation on master
  CODEOWNERS
  governance.Jenkinsfile
  orchestrator.Jenkinsfile
Labels: area/ci, area/community, enhancement, priority/critical
