Repository kyma-project/community, pull requests merged in 2018-12, with the labels that each got.

#141 Create UI API Layer modularization proposal
  sig-and-wg/sig-core/proposals/assets/ui-api-modularization.html
  sig-and-wg/sig-core/proposals/assets/ui-api-modularization.svg
  sig-and-wg/sig-core/proposals/ui-api-layer-modularization.md
Labels: area/community, area/console, sig/core

#131 Application Connectivity capability description
  capabilities/README.md
  capabilities/application-connectivity.md
Labels: area/application-connector, area/documentation

#145 Create wg-kyma-knative
  sig-and-wg/wg-knative/README.md
Labels: area/community, wg/knative

#154 Update wg-knative details
  sig-and-wg/wg-knative/README.md
Labels: area/community

#157 Improve the table with the templates
  guidelines/templates/README.md
Labels: area/documentation

#159 Add guidelines on using command line arguments
  guidelines/content-guidelines/style-and-standards.md
Labels: area/community, area/documentation

#161 Add "Function" to the list of capitalized terms in the guidelines
  guidelines/content-guidelines/style-and-standards.md
Labels: area/documentation

#163 Add new component to the official Kyma documentation
  guidelines/add-new-component-docs.md
Labels: area/documentation, enhancement

#164 Add the size subsection
  guidelines/content-guidelines/diagrams.md
  guidelines/content-guidelines/screenshots.md
Labels: area/documentation

#143 Add proposal about the common libraries concept in Kyma
  milv.config.yaml
  sig-and-wg/sig-core/proposals/common-libraries.md
Labels: decision, sig/core

#168 Add guideline for create linking between docs in kyma/docs dir
  guidelines/content-guidelines/formatting-and-style.md
  guidelines/content-guidelines/linking-in-docs.md
Labels: area/documentation

#172 Fix paragraph in linking-in-docs guideline
  guidelines/content-guidelines/linking-in-docs.md
Labels: area/documentation, bug

#171 Update the decision-making diagram
  assets/decision-making-process.png
  assets/decision-making-process.svg
  assets/decision-making-process.xml
  governance.md
Labels: area/community, area/documentation
