Repository kyma-project/community, pull requests merged in 2018-09, with the labels that each got.

#54 Create a template for the Overview document type
  guidelines/content-guidelines/content-strategy.md
  guidelines/templates/README.md
  guidelines/templates/resources/cli-reference.md
  guidelines/templates/resources/custom-resource.md
  guidelines/templates/resources/overview.md
Labels: area/documentation

#57 Update governance.md with information about kyma incubator
  governance.md
Labels: area/community, area/documentation, enhancement

#58 Create the DR template and move the existing ADRs to SIG Core
  CODEOWNERS
  README.md
  architecture-decision-records/README.md
  guidelines/templates/README.md
  guidelines/templates/resources/ADR.md
  guidelines/templates/resources/DR.md
  guidelines/templates/resources/sig-wg-meeting-notes-template.md
  guidelines/templates/resources/sig-wg-readme-template.md
  milv.config.yaml
  sig-and-wg/README.md
  sig-and-wg/sig-core/decisions/README.md
  sig-and-wg/sig-core/decisions/dr-001-Technologies.md
  sig-and-wg/sig-core/decisions/dr-002-Traefik_as_an_API_Gateway.md
  sig-and-wg/sig-core/decisions/dr-003-InitContainers_for_dependency_management.md
  sig-and-wg/sig-core/decisions/dr-004-Kyma_components_testing.md
  sig-and-wg/sig-core/decisions/dr-005-Istio_as_the_API_Gateway.md
  sig-and-wg/sig-core/decisions/dr-006-Kubeless_as_the_Faas_solution.md
  sig-and-wg/sig-core/decisions/dr-007-GraphQL_as_API_facade_for_UI.md
  sig-and-wg/sig-core/decisions/dr-008-Dex_as_an_OIDC_authenticator.md
  sig-and-wg/sig-core/decisions/dr-009-ServiceBinding_in_Kyma.md
  sig-and-wg/sig-core/decisions/dr-010-JWT_authentication.md
  sig-and-wg/sig-core/decisions/dr-011-Jaeger_as_a_tracing_back-end.md
  sig-and-wg/sig-core/decisions/dr-012-Prettier_as_JavaScript_code_formatter.md
  sig-and-wg/sig-core/decisions/dr-013-Allowed_UI_technology_in_the_Console_UI.md
  sig-and-wg/sig-core/decisions/dr-014-Certificate_against_remote_environment.md
  sig-and-wg/sig-core/decisions/dr-015-Authorization_for_GraphQL.md
  sig-and-wg/sig-core/decisions/dr-016-Decomposition_of_Application_Connector.md
  sig-and-wg/sig-core/decisions/dr-017-Application-Integration-without-Wormhole-Connector.md
  sig-and-wg/sig-core/decisions/dr-018-Knative_based_Kyma_eventing.md
Labels: area/documentation

#68 Introduce changelog generation decision record
  sig-and-wg/sig-core/decisions/dr-019-Changelog_generation_with_PR_labels.md
  sig-and-wg/sig-core/proposals/generating-changelog-with-pr-labels.md
Labels: area/community, area/documentation, enhancement

#73 Update the governance.md document
  assets/decision-making-process.png
  assets/decision-making-process.xml
  governance.md
  guidelines/templates/resources/DR.md
Labels: area/documentation

#59 Update issues-workflow.md with SIG/WG custom labels
  assets/kyma-triage.html
  assets/kyma-triage.svg
  issues-workflow.md
Labels: area/community, area/documentation

#75 Prepare a template for Details document
  guidelines/content-guidelines/content-strategy.md
  guidelines/templates/README.md
  guidelines/templates/resources/details.md
Labels: area/documentation, enhancement
