Repository kyma-project/community, pull requests merged in 2018-11, with the labels that each got.

#124 Add "UI Contracts" type to the community repo
  guidelines/content-guidelines/content-strategy.md
  guidelines/content-guidelines/screenshots.md
  guidelines/templates/resources/getting-started.md
Labels: area/documentation, bug, enhancement

#125 Correct the link
  guidelines/custom-resource-definitions.md
Labels: area/documentation

#126 Update content guidelines to add information on CR formatting
  guidelines/content-guidelines/style-and-standards.md
Labels: area/documentation, enhancement

#127 Correct wrong formatting of CR names in docs
  guidelines/content-guidelines/content-strategy.md
  guidelines/custom-resource-definitions.md
  guidelines/templates/resources/custom-resource.md
  sig-and-wg/sig-core/proposals/application-connector-as-addon.md
Labels: area/documentation

#128 Add capabilities listing with their description
  capabilities/README.md
  capabilities/display-name.md
Labels: area/community
