Repository kyma-project/community, pull requests merged in 2019-03, with the labels that each got.

#232 Fix the links in the community repo templates
  guidelines/templates/resources/architecture.md
  guidelines/templates/resources/cli-reference.md
  guidelines/templates/resources/custom-resource.md
  guidelines/templates/resources/details.md
  guidelines/templates/resources/overview.md
  guidelines/templates/resources/tutorials.md
Labels: area/documentation, bug

#233 Removed an empty doc on golang standards
  guidelines/coding-standards/README.md
  guidelines/coding-standards/golang.md
Labels: area/documentation

#230 Add guideline for using toggle in documentation
  guidelines/content-guidelines/README.md
  guidelines/content-guidelines/assets/toggle_flat_structure.png
  guidelines/content-guidelines/assets/toggle_in_list.png
  guidelines/content-guidelines/documentation-toggle.md
Labels: WIP, area/community, area/documentation, enhancement

#234 Add guideline for using Color Panel in docs
  guidelines/content-guidelines/formatting-and-style.md
Labels: area/documentation

#160 Connector service proposal
  sig-and-wg/sig-core/proposals/assets/connector-service-api.yaml
  sig-and-wg/sig-core/proposals/assets/connector-service-applications-api.png
  sig-and-wg/sig-core/proposals/assets/connector-service-component-diagram.svg
  sig-and-wg/sig-core/proposals/assets/connector-service-flow.svg
  sig-and-wg/sig-core/proposals/assets/connector-service-health-api.png
  sig-and-wg/sig-core/proposals/assets/connector-service-runtimes-api.png
  sig-and-wg/sig-core/proposals/central-connector-service.md
Labels: area/documentation, decision, sig/core

#238 Change the codeowners file
  CODEOWNERS
Labels: area/documentation

#246 Fix asset store proposal link
  sig-and-wg/sig-core/proposals/asset-store-proposal.md
Labels: area/documentation, bug

#237 WG Knative closure
  sig-and-wg/README.md
  sig-and-wg/archive/wg-knative/Closure.md
  sig-and-wg/archive/wg-knative/README.md
  sig-and-wg/archive/wg-knative/assets/asynchronous-workflows.svg
  sig-and-wg/archive/wg-knative/assets/consume.svg
  sig-and-wg/archive/wg-knative/assets/decide-which-pubsub.svg
  sig-and-wg/archive/wg-knative/assets/event-types-future-option3.svg
  sig-and-wg/archive/wg-knative/assets/event-types.svg
  sig-and-wg/archive/wg-knative/assets/extend-application.svg
  sig-and-wg/archive/wg-knative/assets/integrate-3rd-party-consume.svg
  sig-and-wg/archive/wg-knative/assets/integrate-3rd-party-publish.svg
  sig-and-wg/archive/wg-knative/assets/mapping-refer.svg
  sig-and-wg/archive/wg-knative/assets/overview.svg
  sig-and-wg/archive/wg-knative/assets/provisiner.svg
  sig-and-wg/archive/wg-knative/assets/publish-api.svg
  sig-and-wg/archive/wg-knative/knative-eventing-adoption.md
  sig-and-wg/archive/wg-knative/knative-eventing-default-pubsub.md
  sig-and-wg/archive/wg-knative/kyma-eventing-use-case.md
  sig-and-wg/archive/wg-knative/kyma-knative-eventing-examples.md
Labels: decision

#249 Creative Commons license removal
  LICENSE
  guidelines/internal-guidelines/repository-template/README.md
  guidelines/internal-guidelines/repository-template/template/docs/LICENSE
  guidelines/internal-guidelines/repository-template/template/docs/README.md
Labels: area/documentation, quality/content

#251 Improve the content guidelines
  guidelines/content-guidelines/README.md
  guidelines/content-guidelines/formatting.md
  guidelines/content-guidelines/release-notes.md
  guidelines/content-guidelines/style-and-terminology.md
  guidelines/templates/README.md
  milv.config.yaml
Labels: area/documentation, enhancement, quality/content

#250 Describe how Knative channel name is constructed
  sig-and-wg/archive/wg-knative/knative-eventing-adoption.md
Labels: area/eventing
