Repository kyma-project/community, pull requests merged in 2019-08, with the labels that each got.

#325 Fix link
  sig-and-wg/sig-core/proposals/knative-eventing-default-pubsub.md
Labels: area/documentation

#330 Restructure follow-up
  .kyma-project-io/get-started/get-started.md
  README.md
  collaboration/01-sig-and-wg.md
  contributing/02-contributing.md
  contributing/03-git-workflow.md
  governance/01-governance.md
  governance/02-issues-workflow.md
  guidelines/technical-guidelines/03-custom-resource-definitions.md
  guidelines/technical-guidelines/07-test-strategy.md
  guidelines/templates/README.md
  guidelines/templates/resources/release-notes-input.md
Labels: area/documentation, enhancement

#331 Remove internal link from example about security
  guidelines/templates/resources/release-notes-input.md
Labels: area/community, area/security, bug

#332 Fix links
  .github/ISSUE_TEMPLATE/decision-record.md
  .github/ISSUE_TEMPLATE/new-sig-or-wg-proposal.md
Labels: area/documentation

#333 Fix broken link
  guidelines/templates/templates-type.md
Labels: area/documentation

#329 Update image
  guidelines/repository-guidelines/01-new-repository-settings.md
  guidelines/repository-guidelines/assets/prow-webhook.png
Labels: area/documentation, quality/content

#335 Update templates for release notes with info on fixed security vulnerabilities
  guidelines/templates/resources/release-notes.md
Labels: area/documentation, quality/content

#341 Fix link and add .github to repo template
  .gitignore
  guidelines/repository-guidelines/repository-template/.github/ISSUE_TEMPLATE/bug-report.md
  guidelines/repository-guidelines/repository-template/.github/ISSUE_TEMPLATE/feature-request.md
  guidelines/repository-guidelines/repository-template/.github/ISSUE_TEMPLATE/security-vulnerability.md
  guidelines/repository-guidelines/repository-template/.github/issue-template.md
  guidelines/repository-guidelines/repository-template/.github/pull-request-template.md
  guidelines/repository-guidelines/repository-template/.github/stale.yml
  guidelines/repository-guidelines/repository-template/CONTRIBUTING.md
Labels: area/documentation

#342 Fix links
  guidelines/repository-guidelines/02-repository-template.md
Labels: area/documentation

#343 Fix links and formatting
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  guidelines/repository-guidelines/repository-template/CODE_OF_CONDUCT.md
Labels: area/documentation

#345 Correct all errors described
  guidelines/templates/resources/architecture.md
  guidelines/templates/resources/overview.md
Labels: area/documentation, quality/content

#346 Add a missing new line
  guidelines/content-guidelines/01-content-strategy.md
Labels: area/documentation, quality/content

#340 Describe Compass in release instruction
  guidelines/releases-guidelines/02-release-process.md
Labels: enhancement

#338 Document release improvement process
  guidelines/releases-guidelines/02-release-process.md
Labels: area/documentation, quality/release

#348 Fix a typo
  contributing/03-git-workflow.md
Labels: area/documentation

#349 Refactor release process documentation
  guidelines/releases-guidelines/01-release-strategy.md
  guidelines/releases-guidelines/02-kyma-release-process.md
  guidelines/releases-guidelines/02-release-process.md
  guidelines/releases-guidelines/03-kyma-cli-release-process.md
  guidelines/releases-guidelines/04-release-communication.md
  guidelines/releases-guidelines/05-release-process-improvement.md
  guidelines/releases-guidelines/06-release-subscription.md
Labels: area/documentation

#314 knative function integration proposal
  sig-and-wg/sig-core/proposals/assets/knative_function_controller.svg
  sig-and-wg/sig-core/proposals/assets/knative_function_workflow.svg
  sig-and-wg/sig-core/proposals/assets/knative_function_workflow.xml
  sig-and-wg/sig-core/proposals/knative_function_integration.md
Labels: area/community, area/console, area/serverless, decision, sig/core

#352 Prepare a guide to local development with Telepresence
  guidelines/technical-guidelines/08-telepresence-guide.md
Labels: area/documentation, enhancement
