Repository kyma-project/community, pull requests merged in 2019-02, with the labels that each got.

#202 Fix broken link for RN
  guidelines/templates/resources/release-notes.md
Labels: area/documentation

#204 Update the instruction on how to add a new topic to the UI
  guidelines/add-new-component-docs.md
Labels: area/documentation, enhancement

#185 Prepare proposal with common validator for Kyma
  sig-and-wg/sig-core/proposals/common-validator.md
Labels: area/community, area/documentation, decision, enhancement, sig/core

#206 Add lg fixes
  sig-and-wg/sig-core/proposals/asset-store-proposal.md
Labels: area/documentation

#107 Add proposal for kubernetes native headless cms aka new arch for docs solution
  sig-and-wg/sig-core/proposals/assets/main-arch-catalog.svg
  sig-and-wg/sig-core/proposals/assets/main-arch.svg
  sig-and-wg/sig-core/proposals/new-architecture-docs.md
Labels: area/documentation, decision, sig/core

#208 Add Service Brokers doc type to the `content-strategy` document
  guidelines/add-new-component-docs.md
  guidelines/content-guidelines/content-strategy.md
Labels: area/documentation, enhancement

#209 Add minor lg fixes to a proposal
  sig-and-wg/sig-core/proposals/new-architecture-docs.md
Labels: area/documentation

#212 Update changelog generation decision
  sig-and-wg/sig-core/decisions/dr-019-Changelog_generation_with_PR_labels.md
Labels: area/ci, area/community, area/documentation, enhancement

#213 Fix broken links and update doc guideline about linking in docs
  guidelines/content-guidelines/links-in-docs.md
  guidelines/custom-resource-definitions.md
Labels: area/documentation, bug

#215 Fix the dead link
  guidelines/add-monitoring-to-component-docs.md
Labels: area/documentation

#218 Add the release strategy document
  assets/kyma-rel-jobs.svg
  assets/release-PR.png
  guidelines/releases/release-process.md
  guidelines/releases/release-strategy.md
  guidelines/releases/release-subscription.md
Labels: area/documentation

#199 proposal on replacing OKLog with Loki
  sig-and-wg/sig-core/proposals/loki-as-bundled-logging-solution.md
Labels: decision, sig/core

#219 Add Helm guidelines
  guidelines/coding-standards/helm.md
Labels: area/documentation, area/installation

#222 Describe how the Knative channel name is constructed
  sig-and-wg/wg-knative/knative-eventing-adoption.md
Labels: area/eventing

#192 proposal for component folder consolidation
  sig-and-wg/sig-core/proposals/component-folder-consolidation.md
Labels: decision, sig/core

#191 proposal for test folder consolidation
  sig-and-wg/sig-core/proposals/test-folder-consolidation.md
Labels: decision, sig/core

#225 Add minor fixes to README.md
  sig-and-wg/sig-core/README.md
Labels: area/documentation

#138 Eventing capability
  capabilities/README.md
  capabilities/assets/pluggable.png
  capabilities/eventing.md
Labels: area/eventing
