Repository kyma-project/community, pull requests merged in 2019-11, with the labels that each got.

#376 Add more clarification on maintenance rules
  collaboration/01-sig-and-wg.md
  collaboration/02-sig-core.md
  collaboration/sig-core/proposals/assets/knative_function_controller.svg
  collaboration/sig-core/proposals/assets/knative_function_workflow.svg
  collaboration/sig-core/proposals/assets/knative_function_workflow.xml
  collaboration/sig-core/proposals/knative_function_integration.md
  contributing/02-contributing.md
  emeritus.md
  governance/01-governance.md
  governance/02-steering-committee.md
  governance/03-issues-workflow.md
  governance/assets/decision-making-process.svg
Labels: WIP, area/community, enhancement

#399 Add a doc on website preview
  guidelines/content-guidelines/10-docs-preview.md
  guidelines/content-guidelines/assets/failed-preview.png
  guidelines/content-guidelines/assets/job-details.png
  guidelines/content-guidelines/assets/successful-preview.png
Labels: area/documentation

#406 Update the guide for setting branch protection
  guidelines/repository-guidelines/01-new-repository-settings.md
Labels: area/ci, bug

#409 Update community docs on release notes changes
  guidelines/releases-guidelines/02-kyma-release-process.md
  guidelines/templates/resources/release-notes-input.md
  guidelines/templates/resources/release-notes.md
Labels: area/community, area/documentation

#413 Describe rel2rel pipeline in the release process file
  guidelines/releases-guidelines/02-kyma-release-process.md
Labels: area/ci, area/documentation

#416 Remove the API document type
  guidelines/content-guidelines/01-content-strategy.md
Labels: area/application-connector

#415 Improve release document
  guidelines/releases-guidelines/02-kyma-release-process.md
Labels: area/documentation

#375 Combine information about links
  guidelines/content-guidelines/04-formatting.md
  guidelines/content-guidelines/05-links.md
Labels: area/documentation

#407 Removes mention on Scrum of Scrums as they're not open for public
  guidelines/releases-guidelines/04-release-communication.md
Labels: area/community

#419 Add info on flag formatting
  guidelines/content-guidelines/04-formatting.md
Labels: area/documentation, area/quality

#420 Remove "highlights" from RN input template
  guidelines/templates/resources/release-notes-input.md
Labels: area/documentation
