Repository kyma-project/community, pull requests merged in 2019-01, with the labels that each got.

#167 Add release notes templates and guidelines
  guidelines/content-guidelines/README.md
  guidelines/content-guidelines/release-notes.md
  guidelines/templates/README.md
  guidelines/templates/resources/release-notes-input.md
  guidelines/templates/resources/release-notes.md
Labels: area/documentation, enhancement

#173 Capitalize the first listed word
  guidelines/content-guidelines/README.md
Labels: area/documentation

#175 Add information on running Prow tests
  CONTRIBUTING.md
  governance.md
  guidelines/add-new-component-docs.md
  guidelines/content-guidelines/README.md
  guidelines/content-guidelines/formatting-and-style.md
  guidelines/content-guidelines/links-in-docs.md
  milv.config.yaml
Labels: area/documentation

#177 Add Kyma eventing use cases
  sig-and-wg/wg-knative/assets/asynchronous-workflows.svg
  sig-and-wg/wg-knative/assets/extend-application.svg
  sig-and-wg/wg-knative/assets/integrate-3rd-party-consume.svg
  sig-and-wg/wg-knative/assets/integrate-3rd-party-publish.svg
  sig-and-wg/wg-knative/kyma-eventing-use-case.md
Labels: wg/knative

#178 Update the content-strategy.md and mention the fixed docu order
  guidelines/content-guidelines/content-strategy.md
  guidelines/content-guidelines/style-and-standards.md
  guidelines/templates/README.md
  guidelines/templates/resources/getting-started.md
  guidelines/templates/resources/tutorials.md
Labels: area/documentation, enhancement

#181 Fix the broken link
  sig-and-wg/sig-core/proposals/authorization-proxy.md
Labels: area/documentation

#182 knative adoption for Kyma eventing
  sig-and-wg/wg-knative/assets/asynchronous-workflows.svg
  sig-and-wg/wg-knative/assets/consume.svg
  sig-and-wg/wg-knative/assets/event-types-future-option3.svg
  sig-and-wg/wg-knative/assets/event-types.svg
  sig-and-wg/wg-knative/assets/mapping-refer.svg
  sig-and-wg/wg-knative/assets/overview.svg
  sig-and-wg/wg-knative/assets/provisiner.svg
  sig-and-wg/wg-knative/assets/publish-api.svg
  sig-and-wg/wg-knative/knative-eventing-adoption.md
  sig-and-wg/wg-knative/kyma-knative-eventing-examples.md
Labels: area/documentation

#188 Number the document types
  guidelines/content-guidelines/content-strategy.md
  guidelines/templates/resources/architecture.md
  guidelines/templates/resources/cli-reference.md
  guidelines/templates/resources/custom-resource.md
  guidelines/templates/resources/details.md
  guidelines/templates/resources/overview.md
  guidelines/templates/resources/release-notes.md
  guidelines/templates/resources/tutorials.md
Labels: area/documentation

#190 Add information about how we handle stale issues
  issues-workflow.md
Labels: area/community, area/documentation, enhancement

#176 Generic Asset Store proposal
  sig-and-wg/sig-core/proposals/asset-store-proposal.md
  sig-and-wg/sig-core/proposals/assets/gateway.svg
  sig-and-wg/sig-core/proposals/assets/storage.svg
Labels: decision, enhancement, sig/core

#189 Update the sig creation process
  .github/ISSUE_TEMPLATE/new-sig-or-wg-proposal.md
  sig-and-wg/README.md
Labels: area/community

#195 Fix broken links
  sig-and-wg/sig-core/proposals/authorization-proxy.md
  sig-and-wg/sig-core/proposals/modularization.md
Labels: area/documentation

#197 Fix link to decisions board
  governance.md
Labels: area/community, enhancement

#196 Update SIG creation process
  sig-and-wg/README.md
Labels: area/community, area/documentation
