Repository kyma-project/community, pull requests merged in 2019-09, with the labels that each got.

#351 Fix a typo
  guidelines/templates/resources/troubleshooting.md
Labels: area/documentation, bug

#354 Update content guidelines with micro frontend info
  guidelines/content-guidelines/08-style-and-terminology.md
Labels: area/documentation

#356 Change Golang to Go
  collaboration/sig-core/decisions/dr-001-Technologies.md
  collaboration/sig-core/decisions/dr-008-Dex_as_an_OIDC_authenticator.md
  collaboration/sig-core/proposals/central-connector-service.md
  collaboration/sig-core/proposals/common-libraries.md
  collaboration/sig-core/proposals/common-validator.md
  guidelines/technical-guidelines/04-docker-images.md
Labels: area/documentation, quality/content

#358 Update the CRD template
  guidelines/templates/resources/custom-resource.md
Labels: area/documentation, quality/content

#361 Update guidelines with info on ellipsis in code
  guidelines/content-guidelines/04-formatting.md
Labels: area/documentation, quality/content

#364 Move s screenshot and fix formatting
  guidelines/technical-guidelines/05-helm.md
  guidelines/technical-guidelines/assets/metadata-schema.png
Labels: area/documentation

#365 Add info on formatting terms and definitions
  guidelines/content-guidelines/04-formatting.md
Labels: area/community, area/documentation, quality/content

#366 Add missing codeowners
  CODEOWNERS
Labels: area/community, enhancement

#368 Update guidelines with info on the default column in tables
  guidelines/content-guidelines/04-formatting.md
Labels: area/documentation, quality/content

#363 Add new label information
  governance/02-issues-workflow.md
Labels: area/community
