Repository kyma-project/community, pull requests merged in 2019-04, with the labels that each got.

#248 Fix the link to the no-longer-existing doc
  guidelines/content-guidelines/documentation-toggle.md
Labels: area/documentation, bug

#253 Improve the release-notes.md template
  guidelines/templates/resources/release-notes.md
Labels: area/documentation, enhancement, quality/content

#256 Describe how Knative channel name is constructed
  sig-and-wg/archive/wg-knative/knative-eventing-adoption.md
Labels: area/eventing

#257 Update CODEOWNERS
  CODEOWNERS
Labels: area/community, enhancement

#262 Update time zone for Core SIG meeting
  sig-and-wg/sig-core/README.md
Labels: area/documentation

#261 Improve release process instruction
  assets/kyma-rel-jobs.svg
  guidelines/releases/release-process.md
Labels: area/documentation, area/installation, enhancement

#268 Update capabilities - add ids
  capabilities/README.md
  capabilities/api-gateway.md
  capabilities/application-connectivity.md
  capabilities/console-microfrontends.md
  capabilities/core-and-supporting.md
  capabilities/display-name.md
  capabilities/eventing.md
  capabilities/logging-tracing-monitoring.md
  capabilities/service-management.md
Labels: area/community, area/core-and-supporting, enhancement

#270 Fix dead link
  guidelines/add-new-component-docs.md
Labels: area/documentation, bug
