Repository kyma-project/community, pull requests merged in 2019-07, with the labels that each got.

#300 Make release-process.md up to date
  guidelines/releases/release-process.md
Labels: area/documentation

#305 Update formatting.md with how to format metadata names
  guidelines/content-guidelines/formatting.md
Labels: area/documentation

#306 Add instructions on new repo settings
  assets/add-repos.png
  assets/branch-protection-rules.png
  assets/features.png
  assets/merge-button.png
  assets/webhooks.png
  assets/zenhub-webhook-2.png
  assets/zenhub-webhook.png
  governance.md
  guidelines/internal-guidelines/README.md
  guidelines/internal-guidelines/new-repository-settings.md
  guidelines/internal-guidelines/repository-template/README.md
  issues-workflow.md
Labels: area/documentation

#304 Create release communication guidelines
  guidelines/releases/release-communication.md
Labels: area/documentation, quality/release

#308 Create a troubleshooting doc type template
  guidelines/content-guidelines/content-strategy.md
  guidelines/templates/README.md
  guidelines/templates/resources/troubleshooting.md
Labels: area/documentation

#309 Add links to the troubleshooting doc type
  guidelines/content-guidelines/content-strategy.md
  guidelines/templates/README.md
  guidelines/templates/resources/troubleshooting.md
Labels: area/documentation

#311 Remove the old instruction
  guidelines/add-new-component-docs.md
Labels: area/documentation

#315 Rename bundles to addons
  capabilities/service-management.md
Labels: area/documentation

#316 Metadata schema guidelines for helm charts
  assets/metadata-schema.png
  guidelines/coding-standards/helm.md
Labels: area/community, area/documentation, quality/content

#322 Add backup release job to the guide
  guidelines/releases/release-process.md
Labels: area/documentation

#323 Update stale bot settings to exclude epics
  .github/stale.yml
Labels: area/community
