Repository kyma-project/community, pull requests merged in 2019-05, with the labels that each got.

#264 Event Bus monitoring metrics proposal
  sig-and-wg/sig-core/proposals/event-bus-monitoring-metrics.md
Labels: area/documentation, area/monitoring, quality/observability

#263 Proposal about introducing changes to component's code and it's chart…
  sig-and-wg/sig-core/proposals/assets/job-status-checks.png
  sig-and-wg/sig-core/proposals/update-code-and-chart-in-one-pr.md
Labels: quality/productivity, sig/core

#271 Improve instruction on how to link in the docs
  assets/reference-1.png
  assets/reference-2.png
  assets/reference-3.png
  guidelines/content-guidelines/links-in-docs.md
  guidelines/content-guidelines/release-notes.md
Labels: area/documentation, enhancement, quality/content

#272 Improve the release notes template
  guidelines/templates/resources/release-notes.md
Labels: area/documentation

#273 Add a config docs template and update the guidelines
  guidelines/content-guidelines/content-strategy.md
  guidelines/templates/README.md
  guidelines/templates/resources/configuration.md
Labels: area/documentation

#275 Fix link and metadata
  guidelines/templates/README.md
  guidelines/templates/resources/configuration.md
Labels: area/documentation

#277 Update the table formatting guidelines
  guidelines/content-guidelines/formatting.md
  guidelines/templates/resources/custom-resource.md
Labels: area/documentation, enhancement, quality/content

#278 Fix dead links
  guidelines/add-new-component-docs.md
  sig-and-wg/sig-core/proposals/authorization-proxy.md
Labels: area/documentation

#280 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: area/documentation, bug

#282 Update decision making process
  .github/ISSUE_TEMPLATE/decision-record.md
  .github/pull-request-template.md
  assets/decision-making-process.svg
  governance.md
  guidelines/templates/resources/DR.md
  sig-and-wg/sig-core/decisions/README.md
Labels: area/community, area/documentation, enhancement

#286 Correct owner table rendering
  capabilities/README.md
  guidelines/internal-guidelines/repository-template/template/CODEOWNERS
Labels: area/documentation
