Repository kyma-project/community, pull requests merged in 2019-06, with the labels that each got.

#289 Release manual testing
  .gitignore
  guidelines/releases/release-process.md
Labels: area/documentation, quality/release, quality/testability

#295 Update the guidelines re: linking in docs toggles
  guidelines/content-guidelines/assets/toggle_flat_structure.png
  guidelines/content-guidelines/assets/toggle_in_list.png
  guidelines/content-guidelines/documentation-toggle.md
  guidelines/content-guidelines/links-in-docs.md
  milv.config.yaml
Labels: area/community, area/core-and-supporting, area/documentation

#291 Add kyma cli release to the release guidelines
  guidelines/releases/release-process.md
Labels: area/cli, area/documentation, quality/release

#297 Make test strategy public
  guidelines/test-strategy.md
Labels: area/documentation

#299 Release-process.md: rebase and merge
  guidelines/releases/release-process.md
Labels: area/documentation

#302 Update issues-workflow.md
  issues-workflow.md
Labels: area/community, area/documentation, enhancement

#303 Add stale bot
  guidelines/internal-guidelines/repository-template/README.md
  guidelines/internal-guidelines/repository-template/template/stale.yml
Labels: area/documentation
