Repository kyma-project/community, pull requests merged in 2020-10, with the labels that each got.

#514 Fix spelling in the repository name example
  guidelines/content-guidelines/04-formatting.md
Labels: area/documentation, bug

#516 added the description for Kyma Showcase Application WG
  collaboration/wg-showcase-application/README.md
Labels: area/community, area/documentation

#517 Update emeritus file
  emeritus.md
Labels: area/documentation
