Repository kyma-project/community, pull requests merged in 2020-05, with the labels that each got.

#448 Update capability owners
  capabilities/README.md
Labels: area/community, area/documentation

#449 Remove derberg from CODEOWNERS
  CODEOWNERS
Labels: area/community

#463 Update release instructions
  guidelines/releases-guidelines/02-kyma-release-process.md
Labels: area/community, area/documentation

#458 Simplify CLI release process
  guidelines/releases-guidelines/03-kyma-cli-release-process.md
Labels: area/cli, area/documentation
