Repository kyma-project/community, pull requests merged in 2020-07, with the labels that each got.

#483 Update crd guidelines
  guidelines/technical-guidelines/03-custom-resource-definitions.md
Labels: area/documentation

#484 Add Michal Hudy to emeritus
  emeritus.md
Labels: area/community, enhancement

#485 Fix labels in emeritus.md
  emeritus.md
Labels: area/documentation

#489 Update tech lead persona - Sebastian
  manifesto/assets/sebastian.png
  manifesto/personas.md
Labels: area/community, area/documentation, enhancement

#488 Update guideline about CRD
  guidelines/technical-guidelines/03-custom-resource-definitions.md
Labels: area/cluster, area/installation

#490 Update emeritus
  emeritus.md
Labels: area/documentation, enhancement

#491 Add content guidelines on formatting rights as code and spelling cloud-native (adjective)
  guidelines/content-guidelines/04-formatting.md
  guidelines/content-guidelines/08-style-and-terminology.md
Labels: area/documentation, enhancement
