Repository kyma-project/community, pull requests merged in 2021-11, with the labels that each got.

#605 Rename Telemetry Operator CRDs and update examples
  internal/proposals/logs/dynamic-backend-configuration/concept-ServiceCatalog-Integration/images/workflow-overview.svg
  internal/proposals/logs/dynamic-backend-configuration/concept-ServiceCatalog-Integration/serviceCatalogIntegration-Concept.md
  internal/proposals/logs/dynamic-backend-configuration/custom-operator/dynamic-fluentbit-config.md
Labels: size/L, lgtm

#606 Enhance Telemetry Operator CRD examples with system namespace exclusion
  internal/proposals/logs/dynamic-backend-configuration/concept-ServiceCatalog-Integration/serviceCatalogIntegration-Concept.md
Labels: size/S, lgtm

#607 restructured concepts folders
  concepts/README.md
  concepts/installer-migration-hooks/README.md
  concepts/installer-migration-hooks/migration-logic-diagram.drawio
  concepts/installer-migration-hooks/migration-logic-diagram.png
  concepts/observability-configurable-logging/README.md
  concepts/observability-configurable-logging/concept-ServiceCatalog-Integration/images/workflow-overview.svg
  concepts/observability-configurable-logging/concept-ServiceCatalog-Integration/serviceCatalogIntegration-Concept.md
  concepts/observability-configurable-logging/custom-operator/dynamic-fluentbit-config.md
  concepts/observability-configurable-logging/custom-operator/images/fluentbit_CR_overview.drawio
  concepts/observability-configurable-logging/custom-operator/images/fluentbit_CR_overview.svg
  concepts/observability-configurable-logging/custom-operator/images/fluentbit_dynamic_config.drawio
  concepts/observability-configurable-logging/custom-operator/images/fluentbit_dynamic_config.svg
  concepts/observability-configurable-logging/fluent-bit-operator/kubernetes-filter.yaml
  concepts/observability-configurable-logging/fluent-bit-operator/stdout-output.yaml
  concepts/observability-configurable-logging/fluent-bit-operator/tail-input.yaml
  concepts/observability-configurable-logging/fluentbit-operator.md
  concepts/observability-configurable-logging/logging-operator/logging-demo.yaml
  concepts/observability-configurable-logging/logging-operator/loki-flow.yaml
  concepts/observability-configurable-logging/logging-operator/loki-output.yaml
  concepts/observability-configurable-logging/overview.md
  concepts/observability-consistent-logging/README.md
  concepts/observability-consistent-logging/evaluation/apex/apex.go
  concepts/observability-consistent-logging/evaluation/apex/apex_test.go
  concepts/observability-consistent-logging/evaluation/go.mod
  concepts/observability-consistent-logging/evaluation/go.sum
  concepts/observability-consistent-logging/evaluation/k8s/job.yaml
  concepts/observability-consistent-logging/evaluation/test.sh
  concepts/observability-consistent-logging/evaluation/zap/zap.go
  concepts/observability-consistent-logging/evaluation/zerolog/zerolog.go
  concepts/observability-consistent-logging/improvement-of-log-messages-usability.md
  concepts/observability-consistent-logging/logs-stream-destination-and-library-recomendation.md
  concepts/observability-consistent-logging/unified-approach-to-logging-levels.md
  concepts/observability-opentelemetry/README.md
  concepts/observability-opentelemetry/deployment-metrics.md
  concepts/observability-opentelemetry/deployment-tracing.md
  concepts/observability-opentelemetry/deployment/kyma.yaml
  concepts/observability-opentelemetry/deployment/otlc-sidecar.yaml
  concepts/observability-opentelemetry/instrumentation-metrics.md
  concepts/observability-opentelemetry/instrumentation-tracing.md
Labels: size/S, lgtm

#608 Merge three README.md templates into one
  docs/guidelines/templates/templates-type.md
  templates/repository-template/README.md
  templates/resources/example_README.md
Labels: area/documentation, size/M, lgtm

#609 Re-structured configurable logging concept
  concepts/README.md
  concepts/observability-configurable-logging/01-groundwork.md
  concepts/observability-configurable-logging/02-agents.md
  concepts/observability-configurable-logging/03-fluent-bit-operator1.md
  concepts/observability-configurable-logging/04-fluent-bit-operator2.md
  concepts/observability-configurable-logging/05-custom-fluentbit-operator.md
  concepts/observability-configurable-logging/06-servicecatalog-integration.md
  concepts/observability-configurable-logging/README.md
  concepts/observability-configurable-logging/assets/current_all.drawio.svg
  concepts/observability-configurable-logging/assets/fluentbit_CR_overview.drawio.svg
  concepts/observability-configurable-logging/assets/fluentbit_dynamic_config.drawio.svg
  concepts/observability-configurable-logging/assets/future_all.drawio.svg
  concepts/observability-configurable-logging/assets/workflow-overview.drawio.svg
  concepts/observability-configurable-logging/custom-operator/images/fluentbit_CR_overview.drawio
  concepts/observability-configurable-logging/custom-operator/images/fluentbit_CR_overview.svg
  concepts/observability-configurable-logging/custom-operator/images/fluentbit_dynamic_config.drawio
  concepts/observability-configurable-logging/custom-operator/images/fluentbit_dynamic_config.svg
  concepts/observability-consistent-logging/README.md
Labels: size/XXL, lgtm
