Repository kyma-project/community, pull requests merged in 2021-10, with the labels that each got.

#589 Modify CLI release process
  docs/guidelines/releases-guidelines/03-kyma-cli-release-process.md
Labels: area/cli, size/S, lgtm

#592 Use main branch from website
  .kyma-project-io/build-preview.sh
  CODEOWNERS
Labels: size/XS, lgtm

#593 Fix broken links
  .github/ISSUE_TEMPLATE/decision-record.md
  .github/ISSUE_TEMPLATE/new-sig-or-wg-proposal.md
Labels: area/documentation, size/XS, lgtm
