Repository kyma-project/community, pull requests merged in 2021-06, with the labels that each got.

#562 Remove inactive codeowners
  CODEOWNERS
Labels: lgtm, size/XS

#564 Adaptions of JobManager after Discussion
  internal/proposals/migration-hooks/migration-hooks-proposal.md
Labels: lgtm, size/M

#566 Final PoC Draft
  internal/proposals/migration-hooks/migration-hooks-proposal.md
  internal/proposals/migration-hooks/migration-logic-diagram.drawio
  internal/proposals/migration-hooks/migration-logic-diagram.png
Labels: lgtm, size/XS

#567 JobManager PoC - Adaptions after draft implementation
  internal/proposals/migration-hooks/migration-hooks-proposal.md
Labels: lgtm, size/L

#569 Another TW bites the dust
  emeritus.md
Labels: area/community, area/documentation, lgtm, size/XS

#570 adding Julia to emeritus file
  emeritus.md
Labels: lgtm, size/XS
