Repository kyma-project/community, pull requests merged in 2021-07, with the labels that each got.

#573 Apply pull request comments
  governance/03-issues-workflow.md
Labels: lgtm, size/XS

#572 Update issues workflow
  governance/03-issues-workflow.md
Labels: lgtm, size/S

#574 Dynamic Backend Config for Logging Proposal
  internal/proposals/logs/dynamic-backend-configuration/custom-operator/dynamic-fluentbit-config.md
  internal/proposals/logs/dynamic-backend-configuration/custom-operator/images/fluentbit_CR_overview.drawio
  internal/proposals/logs/dynamic-backend-configuration/custom-operator/images/fluentbit_CR_overview.svg
  internal/proposals/logs/dynamic-backend-configuration/custom-operator/images/fluentbit_dynamic_config.drawio
  internal/proposals/logs/dynamic-backend-configuration/custom-operator/images/fluentbit_dynamic_config.svg
  internal/proposals/logs/dynamic-backend-configuration/custom-operator/structs.go
Labels: lgtm, size/L

#575 Rework logging operator CRD
  internal/proposals/logs/dynamic-backend-configuration/custom-operator/dynamic-fluentbit-config.md
  internal/proposals/logs/dynamic-backend-configuration/custom-operator/structs.go
Labels: lgtm, size/M
