Repository kyma-project/community, pull requests merged in 2021-04, with the labels that each got.

#547 Rename master to main
  README.md
  collaboration/sig-core/proposals/asset-store-proposal.md
  collaboration/sig-core/proposals/component-folder-consolidation.md
  collaboration/sig-core/proposals/event-flow.md
  collaboration/sig-core/proposals/new-architecture-docs.md
  collaboration/sig-core/proposals/test-folder-consolidation.md
  collaboration/sig-core/proposals/update-code-and-chart-in-one-pr.md
  governance/03-issues-workflow.md
  guidelines/content-guidelines/03-documentation-toggle.md
  guidelines/content-guidelines/05-links.md
  guidelines/content-guidelines/09-add-new-documentation.md
  guidelines/content-guidelines/README.md
  guidelines/technical-guidelines/02-kyma-components.md
  guidelines/technical-guidelines/03-custom-resource-definitions.md
  guidelines/templates/resources/architecture.md
  guidelines/templates/resources/chart_README.md
  guidelines/templates/resources/cli-reference.md
  guidelines/templates/resources/custom-resource.md
  guidelines/templates/resources/details.md
  guidelines/templates/resources/overview.md
  guidelines/templates/resources/troubleshooting.md
  guidelines/templates/resources/tutorials.md
  guidelines/templates/templates-type.md
Labels: area/documentation

#548 add Nina to community code owners
  CODEOWNERS
Labels: area/documentation, lgtm

#549 Describe OpenTelemetry PoC results for metrics
  internal/research/opentelemetry/README.md
  internal/research/opentelemetry/deployment-metrics.md
  internal/research/opentelemetry/deployment/kyma.yaml
  internal/research/opentelemetry/deployment/otlc-sidecar.yaml
  internal/research/opentelemetry/instrumentation-metrics.md
Labels: lgtm, size/L
