Repository kyma-project/community, pull requests merged in 2021-05, with the labels that each got.

#550 Change master to main (leftovers)
  collaboration/sig-core/proposals/common-validator.md
  collaboration/sig-core/proposals/event-flow.md
  collaboration/sig-core/proposals/update-code-and-chart-in-one-pr.md
  guidelines/technical-guidelines/04-docker-images.md
Labels: lgtm, size/M

#551 Dynamic configuration of logging backends
  internal/proposals/logs/dynamic-backend-configuration/fluent-bit-operator/kubernetes-filter.yaml
  internal/proposals/logs/dynamic-backend-configuration/fluent-bit-operator/stdout-output.yaml
  internal/proposals/logs/dynamic-backend-configuration/fluent-bit-operator/tail-input.yaml
  internal/proposals/logs/dynamic-backend-configuration/logging-operator/logging-demo.yaml
  internal/proposals/logs/dynamic-backend-configuration/logging-operator/loki-flow.yaml
  internal/proposals/logs/dynamic-backend-configuration/logging-operator/loki-output.yaml
  internal/proposals/logs/dynamic-backend-configuration/overview.md
Labels: lgtm, size/L

#552 Add aerfio as emeritus
  emeritus.md
Labels: lgtm, size/XS

#554 Update the emeritus file
  emeritus.md
Labels: area/community, lgtm, size/XS

#558 Update docu with new IS_RELEASE variable
  guidelines/releases-guidelines/03-kyma-cli-release-process.md
Labels: lgtm, size/XS

#560 Migration hook PoC - Introducing the JobManager
  internal/proposals/migration-hooks/migration-hooks-proposal.md
  internal/proposals/migration-hooks/migration-logic-diagram.drawio
  internal/proposals/migration-hooks/migration-logic-diagram.png
Labels: lgtm, size/L
