Repository kyma-project/community, pull requests merged in 2021-08, with the labels that each got.

#577 DR: Remove components proxying requests to Kubernetes API server
  collaboration/sig-core/decisions/dr-007-GraphQL_as_API_facade_for_UI.md
  collaboration/sig-core/decisions/dr-008-Dex_as_an_OIDC_authenticator.md
  collaboration/sig-core/decisions/dr-015-Authorization_for_GraphQL.md
  collaboration/sig-core/decisions/dr-021-Remove-k8s-api-server-proxies.md
Labels: size/M, lgtm

#579 Remove kazydek & superojla from CODEOWNERS
  CODEOWNERS
Labels: area/documentation, area/community, size/XS, lgtm

#582 Update emeritus.md
  emeritus.md
Labels: size/XS, lgtm

#586 Add content strategy after rebase
  .kyma-project-io/build-preview.sh
  docs/guidelines/content-guidelines/01-content-strategy.md
  docs/guidelines/content-guidelines/07-screenshots.md
  docs/guidelines/content-guidelines/assets/screenshot-example-sui.png
  docs/guidelines/templates/README.md
  guidelines/content-guidelines/.DS_Store
  guidelines/templates/resources/concept.md
  guidelines/templates/resources/task.md
  templates/resources/architecture.md
  templates/resources/configuration.md
  templates/resources/custom-resource.md
  templates/resources/troubleshooting.md
Labels: size/L, lgtm
