Repository kyma-project/community, pull requests merged in 2021-01, with the labels that each got.

#525 Propose an improvement of log messages usability
  internal/proposals/logs/improvement-of-log-messages-usability.md
Labels: WIP, area/quality

#528 Propose an unified approach to logging levels
  internal/proposals/logs/unified-approach-to-logging-levels.md
Labels: WIP, area/quality

#531 Fix logging proposals
  internal/proposals/logs/improvement-of-log-messages-usability.md
  internal/proposals/logs/logs-stream-destination-and-library-recomendation.md
  internal/proposals/logs/poc-streams-and-libraries/apex/apex.go
  internal/proposals/logs/poc-streams-and-libraries/apex/apex_test.go
  internal/proposals/logs/poc-streams-and-libraries/go.mod
  internal/proposals/logs/poc-streams-and-libraries/go.sum
  internal/proposals/logs/poc-streams-and-libraries/k8s/job.yaml
  internal/proposals/logs/poc-streams-and-libraries/test.sh
  internal/proposals/logs/poc-streams-and-libraries/zap/zap.go
  internal/proposals/logs/poc-streams-and-libraries/zerolog/zerolog.go
Labels: area/documentation

#532 minor adjustments to messages and external components parts
  internal/proposals/logs/improvement-of-log-messages-usability.md
  internal/proposals/logs/unified-approach-to-logging-levels.md
Labels: area/documentation, area/logging

#537 Add caller information to logging proposals.
  internal/proposals/logs/improvement-of-log-messages-usability.md
  internal/proposals/logs/logs-stream-destination-and-library-recomendation.md
  internal/proposals/logs/poc-streams-and-libraries/apex/apex.go
  internal/proposals/logs/poc-streams-and-libraries/zap/zap.go
  internal/proposals/logs/poc-streams-and-libraries/zerolog/zerolog.go
Labels: area/documentation, enhancement

#522 Removing the Kyma Meetup from website
  collaboration/03-online-meetup.md
Labels: area/documentation

#523 Archiving Kyma Showcase WG
  collaboration/archive/wg-showcase-application/README.md
Labels: area/documentation
