Repository kyma-project/community, pull requests merged in 2022-09, with the labels that each got.

#708 improved drawing for observability strategy
  concepts/observability-strategy/assets/strategy-current.drawio.svg
  concepts/observability-strategy/assets/strategy-future.drawio.svg
  concepts/observability-strategy/configurable-logging/assets/logging-current.drawio.svg
  concepts/observability-strategy/configurable-logging/assets/logging-future.drawio.svg
  concepts/observability-strategy/configurable-monitoring/05-monitoring-concept.md
  concepts/observability-strategy/configurable-monitoring/assets/monitoring-arch.drawio.svg
  concepts/observability-strategy/configurable-monitoring/assets/monitoring-current.drawio.svg
  concepts/observability-strategy/configurable-monitoring/assets/monitoring-future.drawio.svg
  concepts/observability-strategy/configurable-tracing/03-tracing-pocs.md
  concepts/observability-strategy/configurable-tracing/assets/tracing-current.drawio.svg
  concepts/observability-strategy/configurable-tracing/assets/tracing-future.drawio.svg
  concepts/observability-strategy/configurable-tracing/pocs/w3c-tracecontext/README.md
  concepts/observability-strategy/configurable-tracing/pocs/w3c-tracecontext/istio-changes.yaml
  concepts/observability-strategy/configurable-tracing/pocs/w3c-tracecontext/otel-collector.yaml
Labels: size/XXL, lgtm

#709 Admission webhook cert management
  concepts/admission-webhook-cert-management/README.md
  concepts/admission-webhook-cert-management/assets/admission-controller-certs-with-cert-manager.drawio.svg
  concepts/admission-webhook-cert-management/assets/admission-controller-certs.drawio.svg
Labels: size/L, lgtm

#710 Opentelemetry Sampling Rate Test
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-broken-svc-call-summary.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-broken-svc-coredns-cache.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-broken-svc-coredns-overview.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-broken-svc-overwiew.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-broken-svc-resource.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-broken-svc-servicedetail-2.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-broken-svc-servicedetail-3.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-broken-svc-servicedetail.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-call-summary.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-coredns-cache.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-coredns-overview.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-no-svc-call-summary.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-no-svc-coredns-cache.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-no-svc-coredns-overview.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-no-svc-overwiew.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-no-svc-resource.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-no-svc-servicedetail-2.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-no-svc-servicedetail-3.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-no-svc-servicedetail.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-overwiew.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-resource.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-servicedetail-2.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-servicedetail-3.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-100per-servicedetail.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-1per-call-summary.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-1per-coredns-cache.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-1per-coredns-overview.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-1per-overwiew.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-1per-resource.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-1per-servicedetail-2.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-1per-servicedetail-3.jpg
  concepts/observability-strategy/configurable-tracing/assets/istio-1per-servicedetail.jpg
  concepts/observability-strategy/configurable-tracing/pocs/files/apirule.yaml
  concepts/observability-strategy/configurable-tracing/pocs/files/call-simulator/TracingSimulation.java
  concepts/observability-strategy/configurable-tracing/pocs/files/opentelemetry-collector-metric-service-monitor.yaml
  concepts/observability-strategy/configurable-tracing/pocs/files/opentelemetry-collector-metric-service.yaml
  concepts/observability-strategy/configurable-tracing/pocs/files/otel-values.yaml
  concepts/observability-strategy/configurable-tracing/pocs/files/svc-a.yaml
  concepts/observability-strategy/configurable-tracing/pocs/files/svc-b.yaml
  concepts/observability-strategy/configurable-tracing/pocs/files/svc-c.yaml
  concepts/observability-strategy/configurable-tracing/pocs/tracing-sampling-test.md
Labels: area/documentation, area/community, area/tracing, size/XL, lgtm

#712 Tail based sampling
  concepts/observability-strategy/configurable-tracing/03-tracing-pocs.md
Labels: area/tracing, size/S, lgtm

#713 further improved the observability strategy document
  concepts/observability-strategy/assets/strategy-future.drawio.svg
  concepts/observability-strategy/assets/strategy-stages.drawio.svg
  concepts/observability-strategy/configurable-logging/02-logging-collectors.md
  concepts/observability-strategy/configurable-logging/assets/logging-future.drawio.svg
  concepts/observability-strategy/configurable-monitoring/assets/monitoring-future.drawio.svg
  concepts/observability-strategy/configurable-tracing/01-tracing-groundwork.md
  concepts/observability-strategy/configurable-tracing/04-tracing-api.md
  concepts/observability-strategy/configurable-tracing/pocs/w3c-tracecontext/README.md
  concepts/observability-strategy/strategy.md
Labels: size/L, lgtm

#715 improvements to the observabaility strategy
  concepts/observability-strategy/configurable-logging/08-logging-revised-api.md
  concepts/observability-strategy/configurable-monitoring/04-monitoring-api.md
  concepts/observability-strategy/configurable-tracing/02-tracing-collectors.md
  concepts/observability-strategy/configurable-tracing/03-tracing-pocs.md
  concepts/observability-strategy/configurable-tracing/05-tracing-concept.md
  concepts/observability-strategy/configurable-tracing/assets/tracing-future.drawio.svg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/README.md
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-broken-svc-call-summary.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-broken-svc-coredns-cache.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-broken-svc-coredns-overview.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-broken-svc-overwiew.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-broken-svc-resource.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-broken-svc-servicedetail-2.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-broken-svc-servicedetail-3.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-broken-svc-servicedetail.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-call-summary.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-coredns-cache.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-coredns-overview.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-no-svc-call-summary.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-no-svc-coredns-cache.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-no-svc-coredns-overview.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-no-svc-overwiew.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-no-svc-resource.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-no-svc-servicedetail-2.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-no-svc-servicedetail-3.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-no-svc-servicedetail.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-overwiew.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-resource.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-servicedetail-2.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-servicedetail-3.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-100per-servicedetail.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-1per-call-summary.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-1per-coredns-cache.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-1per-coredns-overview.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-1per-overwiew.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-1per-resource.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-1per-servicedetail-2.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-1per-servicedetail-3.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/assets/istio-1per-servicedetail.jpg
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/files/application/apirule.yaml
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/files/application/svc-a.yaml
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/files/application/svc-b.yaml
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/files/application/svc-c.yaml
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/files/call-simulator/TracingSimulation.java
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/files/otel-collector/opentelemetry-collector-metric-service-monitor.yaml
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/files/otel-collector/opentelemetry-collector-metric-service.yaml
  concepts/observability-strategy/configurable-tracing/pocs/sampling-rate/files/otel-collector/otel-values.yaml
  concepts/observability-strategy/strategy.md
Labels: size/L, lgtm

#716 align strategy doc with blog post
  concepts/observability-strategy/assets/integration-custom.drawio.svg
  concepts/observability-strategy/assets/integration-direct.drawio.svg
  concepts/observability-strategy/assets/integration-indirect.drawio.svg
  concepts/observability-strategy/assets/strategy-future.drawio.svg
  concepts/observability-strategy/strategy.md
Labels: area/documentation, size/XL, lgtm

#717 Release channels
  concepts/modularization/README.md
  concepts/modularization/assets/modularization.drawio.svg
  concepts/modularization/assets/operators-example.drawio.svg
  concepts/modularization/assets/release-channels.drawio.svg
Labels: area/documentation, area/community, size/XXL, lgtm

#718 Update CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm
