Repository kyma-project/community, pull requests merged in 2022-05, with the labels that each got.

#662 Update customizations.md
  concepts/observability-automatic-upgrades/customizations.md
Labels: size/XS, lgtm

#661 Add documentation for different logpipeline comparison
  concepts/observability-configurable-logging/05-custom-fluentbit-operator.md
  concepts/observability-configurable-logging/07-multiple-logpipeline-investigation.md
  concepts/observability-configurable-logging/assets/logpipeline-investigation/func.js
  concepts/observability-configurable-logging/assets/logpipeline-investigation/log-generator.yaml
  concepts/observability-configurable-logging/assets/logpipeline-investigation/mock-server.yaml
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-2/loki.yml
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-2/mock-server.yml
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-2/setup-2.drawio.svg
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-2/telemetry-config
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-3a/loki.yml
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-3a/mockserver.yml
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-3a/setup-3a.drawio.svg
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-3b/mockserver-1.yml
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-3b/mockserver-2.yml
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-3b/setup-3b.drawio.svg
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-3c/dashboard-loki-down.png
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-3c/dashboard-mock-down.png
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-3c/loki.yml
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-3c/mock-server.yml
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-3c/setup-3c.drawio.svg
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-3d/dashboard-mock-down.png
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-3d/loki.yml
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-3d/mock-server.yml
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-3d/setup-3d.drawio.svg
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-4/loki.yaml
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-4/mockserver.yml
  concepts/observability-configurable-logging/assets/logpipeline-investigation/setup-4/setup-4.drawio.svg
Labels: size/XXL, lgtm

#665 Remove Prow flow guidelines
  README.md
  docs/README.md
  docs/contributing/04-prow-workflow.md
  docs/contributing/04-sig-and-wg.md
  docs/guidelines/repository-guidelines/01-new-repository-settings.md
  docs/guidelines/repository-guidelines/02-repository-template.md
Labels: area/documentation, area/community, size/L, lgtm, area/prow, kind/cleanup

#664 Create guidelines for UI elements
  docs/guidelines/content-guidelines/04-ui-elements.md
  docs/guidelines/content-guidelines/05-documentation-toggle.md
  docs/guidelines/content-guidelines/06-links.md
  docs/guidelines/content-guidelines/07-release-notes.md
  docs/guidelines/content-guidelines/08-screenshots.md
  docs/guidelines/content-guidelines/09-diagrams.md
  templates/resources/release-notes.md
Labels: area/documentation, size/L, lgtm

#672 Update 02-kyma-release-process.md
  docs/guidelines/releases-guidelines/02-kyma-release-process.md
Labels: size/XS, lgtm

#671 Add the Eventing backend CRD design proposal
  concepts/eventing/backend-crd.md
Labels: size/L, lgtm

#673 Concept: Prometheus custom metrics
  concepts/observability-custom-metrics/README.md
  concepts/observability-custom-metrics/assets/dashboard.yaml
  concepts/observability-custom-metrics/assets/simple-prometheus-setup.yaml
  concepts/observability-custom-metrics/assets/workloads.yaml
Labels: size/XL, lgtm

#674 improve screenshots in community
  docs/guidelines/content-guidelines/assets/screenshot-example-sui.png
  docs/guidelines/content-guidelines/assets/screenshot-example1.png
Labels: size/XS, lgtm
