Repository kyma-project/community, pull requests merged in 2022-08, with the labels that each got.

#693 Update Style+Terminology Guidelines
  docs/guidelines/content-guidelines/02-style-and-terminology.md
Labels: area/documentation, size/L, lgtm

#699 adapt the loki plugin to new changes
  concepts/observability-strategy/configurable-logging/08-logging-revised-api.md
Labels: size/S, lgtm

#701 Transition plan for modularization
  concepts/modularization/README.md
  concepts/modularization/transition.md
Labels: size/M, lgtm

#703 Update emeritus.md
  emeritus.md
Labels: area/documentation, size/XS, lgtm

#705 Respect CLS requirements in the log format recommendations
  concepts/observability-consistent-logging/improvement-of-log-messages-usability.md
Labels: size/XS, lgtm

#654 High-level motivation for operator-based reconciliation
  concepts/operator-reconciliation/README.md
  concepts/operator-reconciliation/assets/centralized_control_plane_configurations.png
  concepts/operator-reconciliation/assets/channel_based_versioning.png
  concepts/operator-reconciliation/assets/detailed_overview_reconciliation.png
  concepts/operator-reconciliation/assets/high_level_view_operator-reconciliation.png
  concepts/operator-reconciliation/assets/lightweight_control_plane_configurations.png
  concepts/operator-reconciliation/assets/single_cluster_configuration.png
Labels: size/L, lgtm

#707 Added more details to configurable tracing concept
  concepts/observability-strategy/assets/strategy-current.drawio.svg
  concepts/observability-strategy/configurable-monitoring/01-monitoring-groundwork.md
  concepts/observability-strategy/configurable-tracing/01-tracing-groundwork.md
  concepts/observability-strategy/configurable-tracing/02-tracing-collectors.md
  concepts/observability-strategy/configurable-tracing/03-tracing-pocs.md
  concepts/observability-strategy/configurable-tracing/04-tracing-api.md
  concepts/observability-strategy/configurable-tracing/05-tracing-concept.md
  concepts/observability-strategy/configurable-tracing/README.md
  concepts/observability-strategy/configurable-tracing/assets/tracing-current.drawio.svg
  concepts/observability-strategy/configurable-tracing/assets/tracing-future.drawio.svg
  concepts/observability-strategy/strategy.md
Labels: size/XXL, lgtm
