Repository kyma-project/community, pull requests merged in 2022-10, with the labels that each got.

#720 [Telemetry Operator] - Add results of tracing PoC about deployment options
  concepts/observability-strategy/configurable-tracing/03-tracing-pocs.md
Labels: size/M, lgtm

#722 Fix general documents links in Document types templates
  docs/guidelines/templates/templates-type.md
Labels: size/XS, lgtm

#723 Fix the link to the 'manifest' package
  concepts/modularization/transition.md
Labels: kind/bug, area/documentation, size/XS, lgtm

#724 Update emeritus.md
  emeritus.md
Labels: size/XS, lgtm

#729 Update CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm

#714 Cluster Operator proposal
  concepts/infrastructure-reconciliation/README.md
  concepts/infrastructure-reconciliation/assets/infrastructure-reconciliation.svg
Labels: size/L, lgtm, area/control-plane

#726 Update module operator description and examples
  concepts/modularization/README.md
  concepts/modularization/assets/operators-example.drawio.svg
Labels: size/XXL, lgtm

#727 Support compatibility with Pod Security Standards
  concepts/psp-replacement/README.md
  concepts/psp-replacement/baseline-pod-spec.yaml
  concepts/psp-replacement/restricted-pod-spec.yaml
Labels: area/documentation, area/community, size/L, lgtm

#711 add modularization overview
  concepts/modularization/assets/modular_approach.svg
  concepts/modularization/modularization_overview.md
Labels: area/documentation, size/M, lgtm

#731 Clarify kubeconfig delivery flow for KEB
  concepts/infrastructure-reconciliation/README.md
  concepts/infrastructure-reconciliation/assets/infrastructure-reconciliation.svg
Labels: size/S, lgtm, area/control-plane

#728 Document Eventing Load and Jetstream Throughput Tests
  concepts/eventing/performance evaluation/nats-jetstream/different-cloud-providers/nats-throughput-test.md
  concepts/eventing/performance evaluation/nats-jetstream/different-cloud-providers/results.md
Labels: area/eventing, size/L, lgtm

#732 API Gateway release documentation
  docs/guidelines/releases-guidelines/01-release-strategy.md
  docs/guidelines/releases-guidelines/04-api-gateway-release-process.md
  docs/guidelines/releases-guidelines/05-release-communication.md
  docs/guidelines/releases-guidelines/06-release-process-improvement.md
  docs/guidelines/releases-guidelines/07-release-subscription.md
Labels: size/M, lgtm

#725 Enhance Monitoring and Tracing API concepts
  concepts/observability-strategy/configurable-monitoring/04-monitoring-api.md
  concepts/observability-strategy/configurable-tracing/04-tracing-api.md
Labels: size/L, lgtm
