Repository kyma-project/community, pull requests merged in 2022-12, with the labels that each got.

#750 Fix the links to the repository template
  docs/guidelines/repository-guidelines/README.md
  docs/guidelines/templates/templates-type.md
Labels: size/XS, lgtm

#751 Update community docs 131222
  docs/README.md
  docs/contributing/02-contributing.md
Labels: size/S, lgtm

#752 Add nataliasitko to codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#753 Language corrections
  docs/governance/01-governance.md
Labels: area/documentation, area/community, size/M, lgtm
