Repository kyma-project/community, pull requests merged in 2022-01, with the labels that each got.

#617 Emeritus file update
  emeritus.md
Labels: size/XS, lgtm

#618 Add sayanh and suleymanakbas91 to emeritus file
  emeritus.md
Labels: size/XS, lgtm

#616 Update release docs
  docs/guidelines/releases-guidelines/02-kyma-release-process.md
Labels: size/M, lgtm

#619 Update guidelines on formatting CR names
  docs/guidelines/content-guidelines/02-style-and-terminology.md
  docs/guidelines/content-guidelines/03-formatting.md
Labels: size/S, lgtm

#620 Add grego952 as a documentation CODEOWNER in Community
  CODEOWNERS
Labels: area/documentation, area/community, size/XS, lgtm

#622 Fix governance `too many requests` error
  milv.config.yaml
Labels: size/XS, lgtm

#621 add adamwalach to emeritus file
  emeritus.md
Labels: size/XS, lgtm

#623 Add instructions to updated Homebrew formula
  docs/guidelines/releases-guidelines/03-kyma-cli-release-process.md
Labels: size/S, lgtm
