Repository kyma-project/community, pull requests merged in 2022-07, with the labels that each got.

#687 Fixed spelling mistake in doc
  concepts/eventing/performance evaluation/nats-jetstream/results_prod_HA.md
Labels: size/XS, lgtm

#685 Configurable Monitoring Concept Proposal
  concepts/observability-configurable-monitoring/01-groundwork.md
  concepts/observability-configurable-monitoring/02-agents.md
  concepts/observability-configurable-monitoring/03-pocs.md
  concepts/observability-configurable-monitoring/04-api.md
  concepts/observability-configurable-monitoring/05-concept.md
  concepts/observability-configurable-monitoring/README.md
  concepts/observability-configurable-monitoring/assets/arch.drawio.svg
  concepts/observability-configurable-monitoring/assets/current.drawio.svg
  concepts/observability-configurable-monitoring/assets/future.drawio.svg
  concepts/observability-configurable-monitoring/pocs/scrape-scalability/README.md
  concepts/observability-configurable-monitoring/pocs/scrape-scalability/otel-collector-values-daemonset.yaml
  concepts/observability-configurable-monitoring/pocs/scrape-scalability/otel-collector-values-deployment.yaml
  concepts/observability-configurable-monitoring/pocs/scrape-scalability/prometheus.yaml
Labels: size/XXL, lgtm

#692 Update 01-new-repository-settings.md
  docs/guidelines/repository-guidelines/01-new-repository-settings.md
Labels: area/documentation, size/XS, lgtm

#696 Update emeritus.md
  emeritus.md
Labels: size/XS, lgtm

#666 Modularization concept
  concepts/modularization/README.md
  concepts/modularization/assets/modularization.drawio.svg
  concepts/modularization/assets/operators-example.drawio.svg
Labels: size/XL, lgtm
