Repository kyma-project/community, pull requests merged in 2022-11, with the labels that each got.

#734 Fix broken link in observability logging
  concepts/observability-consistent-logging/logs-stream-destination-and-library-recomendation.md
Labels: area/documentation, size/XS, lgtm

#735 Update CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm

#733 Update 01-governance.md
  docs/governance/01-governance.md
Labels: size/XS, lgtm

#737 revert codeowners changes
  CODEOWNERS
Labels: size/XS, lgtm

#740 Add Wojciech Chrapka to emeritus
  emeritus.md
Labels: size/XS, lgtm

#739 Update 01-governance.md
  docs/governance/01-governance.md
Labels: size/XS, lgtm

#741 fix links to template operator
  concepts/modularization/modularization_overview.md
  concepts/modularization/transition.md
Labels: size/XS, lgtm

#743 Remove the `manifesto-app` from the CODEOENWRS
  CODEOWNERS
Labels: size/XS, lgtm

#744 adding missing emeritus
  emeritus.md
Labels: size/XS, lgtm

#745 remove Maja from codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#746 Update release guidelines for api-gateway
  docs/guidelines/releases-guidelines/04-api-gateway-release-process.md
Labels: size/XS, lgtm

#736 Modularization concept update
  concepts/modularization/README.md
  concepts/modularization/assets/release-channels.drawio.svg
Labels: size/L, lgtm

#747 Update CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm
