Repository kyma-project/community, pull requests merged in 2022-04, with the labels that each got.

#643 Update guidelines about creating a new repository
  docs/guidelines/repository-guidelines/01-new-repository-settings.md
  docs/guidelines/repository-guidelines/02-repository-template.md
  docs/guidelines/repository-guidelines/assets/template.png
  templates/repository-template/.github/ISSUE_TEMPLATE/bug-report.md
  templates/repository-template/.github/ISSUE_TEMPLATE/decision-record.md
  templates/repository-template/.github/ISSUE_TEMPLATE/documentation-improvement.md
  templates/repository-template/.github/ISSUE_TEMPLATE/feature-request.md
  templates/repository-template/.github/ISSUE_TEMPLATE/new-sig-or-wg-proposal.md
  templates/repository-template/.github/ISSUE_TEMPLATE/security-vulnerability.md
  templates/repository-template/.github/issue-template.md
  templates/repository-template/.github/pull-request-template.md
  templates/repository-template/.github/stale.yml
  templates/repository-template/CODEOWNERS
  templates/repository-template/CODE_OF_CONDUCT.md
  templates/repository-template/CONTRIBUTING.md
  templates/repository-template/LICENSE
  templates/repository-template/NOTICE.md
  templates/repository-template/README.md
  templates/repository-template/docs/README.md
Labels: size/XL, lgtm

#652 Add Pranav Shankar and Radu Fantaziu
  emeritus.md
Labels: area/community, size/XS, lgtm

#655 Add section about adding or removing people from OWNERS file
  docs/contributing/04-prow-workflow.md
Labels: size/S, lgtm

#653 Enhance cli release doc
  docs/guidelines/releases-guidelines/03-kyma-cli-release-process.md
Labels: size/XS, lgtm

#657 Bug fixes should be included on main and release branch
  docs/guidelines/releases-guidelines/02-kyma-release-process.md
Labels: area/documentation, size/XS, lgtm

#656 Extended configurable logging concept
  concepts/observability-configurable-logging/05-custom-fluentbit-operator.md
Labels: size/L, lgtm

#660 Change contact persons for the release process
  docs/guidelines/releases-guidelines/04-release-communication.md
Labels: size/XS, lgtm

#659 Document Telemetry Fluent Bit customizatons
  concepts/observability-automatic-upgrades/customizations.md
Labels: size/S, lgtm
