Repository kyma-project/community, pull requests merged in 2022-03, with the labels that each got.

#630 Eventing team code guidelines conclusion
  concepts/eventing-code-guidelines.md
Labels: area/eventing, size/M, lgtm

#634 Document results from team discussions for eventing team code guidelines
  concepts/eventing-code-guidelines.md
Labels: area/eventing, size/XS, lgtm

#635 Update emeritus.md
  emeritus.md
Labels: area/community, size/XS, lgtm

#638 Update emeritus.md
  emeritus.md
Labels: size/XS, lgtm

#639 Update CONTRIBUTING.md
  templates/repository-template/CONTRIBUTING.md
Labels: kind/bug, area/community, size/XS, lgtm

#636 Infrastructure reconciliation
  concepts/infrastructure-reconciliation/README.md
  concepts/infrastructure-reconciliation/assets/infrastructure-reconciliation.svg
Labels: size/L, lgtm

#641 Update the Style and Terminology content guidelines
  docs/guidelines/content-guidelines/02-style-and-terminology.md
Labels: area/documentation, size/XS, lgtm

#637 Change how to write 2-dimensional table-tests
  concepts/eventing-code-guidelines.md
Labels: area/eventing, size/L, lgtm

#646 Add Kyma runtime logo to assets
  templates/resources/assets/kyma_runtime_logo.svg
Labels: area/documentation, area/community, size/XS, lgtm

#648 Updates the guidelines to use natural language for resource names
  docs/guidelines/content-guidelines/02-style-and-terminology.md
  docs/guidelines/content-guidelines/08-diagrams.md
  docs/guidelines/content-guidelines/assets/~$diagram-example.svg.bkp
Labels: area/documentation, size/S, lgtm

#649 Fix the example diagram update in content guidelines
  docs/guidelines/content-guidelines/assets/diagram-example.svg
  docs/guidelines/content-guidelines/assets/~$diagram-example.svg.bkp
Labels: kind/bug, area/documentation, size/XS, lgtm

#650 Fix a typo
  docs/guidelines/content-guidelines/08-diagrams.md
Labels: kind/bug, area/documentation, size/XS, lgtm

#647 Prow workflow docs
  README.md
  docs/README.md
  docs/contributing/03-git-workflow.md
  docs/contributing/04-prow-workflow.md
  docs/contributing/05-sig-and-wg.md
Labels: size/M, lgtm
