Repository kyma-project/community, pull requests merged in 2022-06, with the labels that each got.

#676 remove kyma1 from cli release guide
  docs/guidelines/releases-guidelines/03-kyma-cli-release-process.md
Labels: size/S, lgtm

#682 Add Pooya Salehi to emeritus file
  emeritus.md
Labels: size/XS, lgtm

#678 Add missing doc-regeneration step
  docs/guidelines/releases-guidelines/03-kyma-cli-release-process.md
Labels: size/XS, lgtm

#675 adjustments for configurable logging
  concepts/observability-configurable-logging/08-revised-api.md
  concepts/observability-configurable-logging/README.md
Labels: size/L, lgtm

#677 Added performance evaluation results of NATS JetStream
  concepts/eventing/performance evaluation/nats-jetstream/assets/01_06_22-10-150_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/01_06_22-10-150_2.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/01_06_22-10-150_3.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/01_06_22-10-200_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/01_06_22-10-200_2.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/01_06_22-10-200_3.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/01_06_22-10-250_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/02_06_22-10-1000_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/02_06_22-10-250_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/02_06_22-10-250_2.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/1000+loss3run.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/1000_loss1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/NATS_07_06_22-10-150_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/crash1_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/crash1_2.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/crash1_3.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/crash1_4.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/crash2_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/crash2_2.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/crash2_3.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/crash2_4.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/crash3_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/crash3_2.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/crash3_3.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/crash3_4.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/eval_03_06_22-10-100_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/eval_03_06_22-10-100_2.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/eval_03_06_22-10-50_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/eval_03_06_22-10-50_2.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/eval_crash1_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/eval_crash1_2.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/eval_crash1_3.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/eval_crash1_4.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/eval_crash2_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/eval_crash2_2.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/eval_crash2_3.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/eval_crash2_4.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/eval_crash3_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/eval_crash3_2.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/eval_crash3_3.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/eval_crash3_4.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/jetstream_dash1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/loss_1000_consumer.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/loss_1000_stream.png
  concepts/eventing/performance evaluation/nats-jetstream/investigation-discrepancy.md
  concepts/eventing/performance evaluation/nats-jetstream/results_eval.md
  concepts/eventing/performance evaluation/nats-jetstream/results_prod.md
Labels: area/eventing, size/L, lgtm

#683 Added HA evaluation results for NATS Jetstream
  concepts/eventing/performance evaluation/nats-jetstream/assets/ha_crash1_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/ha_crash1_2.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/ha_crash2_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/ha_crash2_2.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/ha_crash3_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/ha_crash3_2.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/ha_crash4_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/ha_crash4_2.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/ha_crash5_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/ha_crash5_2.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/ha_crash5_3.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/ha_crash6_1.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/ha_crash6_2.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/ha_crash6_3.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/ha_crash6_4.png
  concepts/eventing/performance evaluation/nats-jetstream/assets/ha_crash6_5.png
  concepts/eventing/performance evaluation/nats-jetstream/results_eval.md
  concepts/eventing/performance evaluation/nats-jetstream/results_prod.md
  concepts/eventing/performance evaluation/nats-jetstream/results_prod_HA.md
Labels: area/eventing, size/L, lgtm
