Repository kyma-project/community, pull requests merged in 2023-10, with the labels that each got.

#843 Add release notes for Kyma 2.19
  docs/kyma-release-notes/2023-10-02-release-notes-2.19.md
Labels: size/M, lgtm

#846 Remove milv config file
  milv.config.yaml
Labels: size/S, lgtm

#844 Gh actions
  docs/contributing/05-gh-actions.md
  docs/contributing/assets/allowed_actions.json
  docs/contributing/assets/gh-actions-permissions.png
  docs/contributing/scorecard-ratings/AbsaOSS_k3d-action.json
  docs/contributing/scorecard-ratings/CondeNast_conventional-pull-request-action.json
  docs/contributing/scorecard-ratings/ahmadnassri_action-workflow-queue.json
  docs/contributing/scorecard-ratings/autotelic_action-wait-for-status-check.json
  docs/contributing/scorecard-ratings/gaurav-nelson_github-action-markdown-link-check.json
  docs/contributing/scorecard-ratings/golangci_golangci-lint-action.json
  docs/contributing/scorecard-ratings/golangci_golangci-lint.json
  docs/contributing/scorecard-ratings/mfaizanse_wait-for-git-commit-status-action.json
  docs/contributing/scorecard-ratings/shmokmt_actions-setup-github-comment.json
  docs/contributing/scorecard-ratings/shmokmt_actions-setup-tfcmt.json
  docs/contributing/scorecard-ratings/slackapi_slack-github-action.json
  docs/contributing/scorecard-ratings/suzuki-shunsuke_github-comment.json
  docs/contributing/scorecard-ratings/suzuki-shunsuke_tfcmt.json
  docs/contributing/scorecard-ratings/tcort_markdown-link-check.json
  docs/contributing/scorecard-ratings/zgosalvez_github-actions-ensure-sha-pinned-actions.json
Labels: size/XXL, lgtm

#847 Fix broken links
  docs/guidelines/repository-guidelines/01-new-repository-settings.md
  emeritus.md
Labels: size/XS, lgtm

#848 Update CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm

#842 NFS storage concept
  concepts/nfs-storage/README.md
  concepts/nfs-storage/nfs-own-vpc.drawio.svg
  concepts/nfs-storage/nfs-shoot-vpc.drawio.svg
Labels: size/L, lgtm

#849 Update README.md
  concepts/nfs-storage/README.md
Labels: size/XS, lgtm

#851 Update codeowners
  CODEOWNERS
Labels: area/security, size/XS, lgtm, kind/chore

#855 Whitelist amannn/action-semantic-pull-request 5.3.0
  docs/contributing/assets/allowed_actions.json
Labels: size/XS, lgtm
