Repository kyma-project/community, pull requests merged in 2023-01, with the labels that each got.

#756 Introduce Kyma Module Provider
  concepts/modularization/README.md
  concepts/modularization/assets/release-channels.drawio.svg
  concepts/modularization/transition.md
Labels: area/documentation, size/L, lgtm

#758 Remove outdated release process documentation
  docs/guidelines/releases-guidelines/02-kyma-release-process.md
Labels: size/XS, lgtm

#755 Modularization - migration process
  concepts/modularization/assets/migration.drawio.svg
  concepts/modularization/migration.md
Labels: size/L, lgtm
