Repository kyma-project/community, pull requests merged in 2023-08, with the labels that each got.

#812 Fix broken links
  docs/kyma-release-notes/2023-08-04-release-notes-2.17.md
  emeritus.md
Labels: area/documentation, size/XS, lgtm

#813 Update contributing file to meet OSPO requirements
  docs/contributing/02-contributing.md
Labels: size/M, lgtm

#814 Update links for the domain change
  docs/guidelines/content-guidelines/01-content-strategy.md
  docs/guidelines/content-guidelines/05-documentation-toggle.md
  docs/guidelines/content-guidelines/10-docs-preview.md
  sigs-and-wgs/archive/sig-core/proposals/authorization-proxy.md
  sigs-and-wgs/archive/sig-core/proposals/event-flow.md
  templates/resources/architecture.md
  templates/resources/configuration.md
  templates/resources/custom-resource.md
Labels: size/S, lgtm

#821 reuse compliance
  LICENSES/Apache-2.0.txt
  README.md
Labels: size/M, lgtm

#825 Add Release Notes for 2.17.1
  docs/kyma-release-notes/2023-08-24-release-notes-2.17.1.md
Labels: size/XS, lgtm

#829 Update 02-kyma-release-process.md
  docs/guidelines/releases-guidelines/02-kyma-release-process.md
Labels: size/M, lgtm

#830 Add release notes for Kyma 2.18
  docs/kyma-release-notes/2023-08-31-release-notes-2.18.md
Labels: area/documentation, size/M, lgtm
