Repository kyma-project/community, pull requests merged in 2023-09, with the labels that each got.

#832 Update community guidelines
  docs/README.md
  docs/guidelines/content-guidelines/00-content-strategy.md
  docs/guidelines/content-guidelines/01-user-docs.md
  docs/guidelines/content-guidelines/05-documentation-toggle.md
  docs/guidelines/content-guidelines/05-tabs-toggles.md
  docs/guidelines/content-guidelines/06-links.md
  docs/guidelines/content-guidelines/07-release-notes.md
  docs/guidelines/content-guidelines/10-docs-preview.md
  docs/guidelines/content-guidelines/assets/toggle-flat-structure.png
  docs/guidelines/content-guidelines/assets/toggle_in_list.png
Labels: area/documentation, size/XL, lgtm

#833 minor language fixes
  docs/guidelines/content-guidelines/01-user-docs.md
Labels: size/S, lgtm

#828 Add info about the usage of Github Actions
  docs/contributing/05-gh-actions.md
  docs/contributing/assets/GitHub-Actions-Security-Best-Practices_cheatsheet-1.png
  docs/contributing/assets/GitHub-Actions-Security-Best-Practices_cheatsheet.pdf
  docs/contributing/assets/gh-actions-peermissions.png
  docs/contributing/assets/gh-actions-policies.png
  docs/contributing/scorecard-ratings/AbsaOSS_k3d-action.json
  docs/contributing/scorecard-ratings/CondeNast_conventional-pull-request-action.json
  docs/contributing/scorecard-ratings/ahmadnassri_action-workflow-queue.json
  docs/contributing/scorecard-ratings/autotelic_action-wait-for-status-check.json
  docs/contributing/scorecard-ratings/gaurav-nelson_github-action-markdown-link-check.json
  docs/contributing/scorecard-ratings/golangci_golangci-lint-action.json
  docs/contributing/scorecard-ratings/golangci_golangci-lint.json
  docs/contributing/scorecard-ratings/mfaizanse_wait-for-git-commit-status-action.json
  docs/contributing/scorecard-ratings/shmokmt_actions-setup-github-comment.json
  docs/contributing/scorecard-ratings/shmokmt_actions-setup-tfcmt.json
  docs/contributing/scorecard-ratings/slackapi_slack-github-action.json
  docs/contributing/scorecard-ratings/suzuki-shunsuke_github-comment.json
  docs/contributing/scorecard-ratings/suzuki-shunsuke_tfcmt.json
  docs/contributing/scorecard-ratings/tcort_markdown-link-check.json
  docs/contributing/scorecard-ratings/zgosalvez_github-actions-ensure-sha-pinned-actions.json
Labels: size/XXL, lgtm

#837 Fix links detected by the Daily Markdown Link Check
  README.md
  concepts/installer-migration-hooks/README.md
  concepts/observability-strategy/configurable-logging/03-fluent-bit-operator1.md
  docs/README.md
  docs/governance/01-governance.md
  docs/governance/03-issues-workflow.md
  docs/guidelines/content-guidelines/06-links.md
  docs/guidelines/content-guidelines/10-docs-preview.md
  docs/guidelines/releases-guidelines/01-release-strategy.md
  docs/guidelines/releases-guidelines/02-kyma-release-process.md
  docs/guidelines/releases-guidelines/03-kyma-cli-release-process.md
  docs/guidelines/releases-guidelines/07-release-subscription.md
  docs/guidelines/repository-guidelines/01-new-repository-settings.md
  sigs-and-wgs/archive/sig-core/decisions/README.md
  sigs-and-wgs/archive/sig-core/decisions/dr-008-Dex_as_an_OIDC_authenticator.md
  sigs-and-wgs/archive/sig-core/decisions/dr-015-Authorization_for_GraphQL.md
  sigs-and-wgs/archive/sig-core/decisions/dr-021-Remove-k8s-api-server-proxies.md
  sigs-and-wgs/archive/sig-core/proposals/asset-store-proposal.md
  sigs-and-wgs/archive/sig-core/proposals/image-name-consolidation.md
  sigs-and-wgs/archive/sig-core/proposals/knative-eventing-default-pubsub.md
  sigs-and-wgs/archive/sig-core/proposals/modularization.md
  sigs-and-wgs/archive/sig-core/proposals/new-architecture-docs.md
  sigs-and-wgs/archive/sig-core/proposals/update-code-and-chart-in-one-pr.md
  sigs-and-wgs/archive/wg-installation/CLOSURE.md
  sigs-and-wgs/archive/wg-installation/README.md
  sigs-and-wgs/archive/wg-prow/README.md
  sigs-and-wgs/archive/wg-showcase-application/README.md
  templates/resources/sig-wg-readme-template.md
Labels: size/M, lgtm

#838 Update repository guidelines
  .github/workflows/lint-markdown-links-daily.yml
  .github/workflows/lint-markdown-links-pr.yml
  .gitignore
  docs/guidelines/repository-guidelines/01-new-repository-settings.md
  docs/guidelines/repository-guidelines/02-repository-template.md
Labels: area/documentation, size/M, lgtm

#839 Update links and fix formatting
  docs/guidelines/repository-guidelines/01-new-repository-settings.md
  docs/guidelines/repository-guidelines/02-repository-template.md
Labels: size/XS, lgtm

#840 Fix formatting
  docs/guidelines/repository-guidelines/01-new-repository-settings.md
Labels: size/XS, lgtm

#841 Update release docs
  docs/guidelines/releases-guidelines/01-release-strategy.md
  docs/guidelines/releases-guidelines/02-kyma-release-process.md
  docs/guidelines/technical-guidelines/02-docker-images.md
  docs/guidelines/technical-guidelines/03-custom-resource-definitions.md
  docs/guidelines/technical-guidelines/03-helm.md
  docs/guidelines/technical-guidelines/04-http-api-design.md
  docs/guidelines/technical-guidelines/05-test-strategy.md
Labels: area/documentation, size/L, lgtm, kind/cleanup
