Repository kyma-project/community, pull requests merged in 2023-07, with the labels that each got.

#806 Update OCM link
  concepts/modularization/README.md
Labels: size/XS

#804 Add release notes for Kyma 2.16
  docs/kyma-release-notes/2023-07-05-release-notes-2.16.md
Labels: size/M, lgtm

#810 Change the background color of the example diagram
  docs/guidelines/content-guidelines/assets/diagram-example.svg
Labels: size/XS, lgtm
