Repository kyma-project/community, pull requests merged in 2023-04, with the labels that each got.

#772 Add qbalukom
  emeritus.md
Labels: size/XS, lgtm

#773 Update emeritus.md
  emeritus.md
Labels: size/XS, lgtm

#776 Update the migration process
  concepts/modularization/assets/migration.drawio.svg
  concepts/modularization/migration.md
Labels: size/L, lgtm

#780 Update on observability strategy
  CODEOWNERS
  concepts/observability-strategy/README.md
  concepts/observability-strategy/assets/strategy-future-components.drawio.svg
  concepts/observability-strategy/configurable-monitoring/01-monitoring-groundwork.md
  concepts/observability-strategy/configurable-monitoring/02-monitoring-collectors.md
  concepts/observability-strategy/configurable-monitoring/03-monitoring-pocs.md
  concepts/observability-strategy/configurable-monitoring/04-monitoring-api.md
  concepts/observability-strategy/configurable-monitoring/05-monitoring-concept.md
  concepts/observability-strategy/configurable-monitoring/assets/monitoring-future-components.drawio.svg
  concepts/observability-strategy/configurable-monitoring/assets/monitoring-future.drawio.svg
  concepts/observability-strategy/configurable-monitoring/pocs/scrape-scalability/README.md
  concepts/observability-strategy/strategy.md
  concepts/observability-strategy/target-architecture.md
Labels: size/XXL, lgtm

#782 Reorder contributing steps
  docs/contributing/02-contributing.md
Labels: size/S, lgtm
