Repository kyma-project/community, pull requests merged in 2023-02, with the labels that each got.

#759 As automatic upgrades are not in focus anymore, remove the folder
  concepts/observability-automatic-upgrades/customizations.md
Labels: size/S, lgtm

#760 Update emeritus.md
  emeritus.md
Labels: size/XS, lgtm

#761 cleanup of outdated component guide and telepresence guide
  docs/guidelines/technical-guidelines/02-kyma-components.md
  docs/guidelines/technical-guidelines/08-telepresence-guide.md
Labels: size/M, lgtm
