Repository kyma-project/community, pull requests merged in 2023-11, with the labels that each got.

#857 Add release note for Kyma 2.20
  docs/kyma-release-notes/2023-11-08-release-notes-2.20.md
Labels: size/S, lgtm

#859 Fix a broken link
  concepts/observability-strategy/configurable-logging/03-fluent-bit-operator1.md
Labels: size/XS, lgtm

#858 Add action to the whitelist
  docs/contributing/assets/allowed_actions.json
Labels: area/ci, size/S, lgtm, kind/chore

#860 Fix a link
  docs/guidelines/content-guidelines/08-screenshots.md
Labels: area/documentation, size/XS, lgtm

#861 Fix a link
  docs/guidelines/content-guidelines/04-ui-elements.md
Labels: area/documentation, size/XS, lgtm

#862 fix broken banzaicloud link
  concepts/observability-strategy/configurable-logging/03-fluent-bit-operator1.md
Labels: size/S, lgtm, cla: yes
