Repository kyma-project/community, pull requests merged in 2023-06, with the labels that each got.

#794 Update README.md
  concepts/modularization/README.md
Labels: size/M

#796 Update 2023-06-07-release-notes-2.15.md
  docs/kyma-release-notes/2023-06-07-release-notes-2.15.md
Labels: size/XS, lgtm

#797 Update 2023-06-07-release-notes-2.15.md
  docs/kyma-release-notes/2023-06-07-release-notes-2.15.md
Labels: size/XS, lgtm

#798 Add ORY Hydra section
  docs/kyma-release-notes/2023-06-07-release-notes-2.15.md
Labels: size/S, lgtm

#802 Update 2023-06-07-release-notes-2.15.md
  docs/kyma-release-notes/2023-06-07-release-notes-2.15.md
Labels: size/S, lgtm

#793 Add release notes for Kyma 2.15
  docs/kyma-release-notes/2023-06-07-release-notes-2.15.md
Labels: size/M, lgtm

#800 Modularization
  concepts/modularization/README.md
  concepts/modularization/assets/release-channels.drawio.svg
Labels: size/M, lgtm

#803 Add release notes for Kyma 2.15.1
  docs/kyma-release-notes/2023-06-26-release-notes-2.15.1.md
Labels: size/XS, lgtm
