Repository kyma-project/community, pull requests merged in 2023-12, with the labels that each got.

#863 Remove outdated API Gateway release documentation
  docs/guidelines/releases-guidelines/04-api-gateway-release-process.md
Labels: size/M, lgtm, cla: yes

#865 Whitelist latest version of github-actions-ensure-sha-pinned-actions
  docs/contributing/assets/allowed_actions.json
Labels: area/ci, size/XS, lgtm, cla: yes

#866 Update content guidelines
  README.md
  docs/README.md
  docs/guidelines/content-guidelines/00-content-strategy.md
  docs/guidelines/content-guidelines/01-user-docs.md
  docs/guidelines/content-guidelines/02-style-and-terminology.md
  docs/guidelines/content-guidelines/03-formatting.md
  docs/guidelines/content-guidelines/04-ui-elements.md
  docs/guidelines/content-guidelines/05-tabs-toggles.md
  docs/guidelines/content-guidelines/06-links.md
  docs/guidelines/content-guidelines/07-release-notes.md
  docs/guidelines/content-guidelines/08-screenshots.md
  docs/guidelines/content-guidelines/09-diagrams.md
  docs/guidelines/content-guidelines/10-docs-preview.md
  docs/guidelines/content-guidelines/README.md
Labels: area/documentation, lgtm, cla: yes

#867 Remove API Micro Gateway from content guidelines
  docs/guidelines/content-guidelines/02-style-and-terminology.md
Labels: size/XS, lgtm, cla: yes

#869 Fix link in the telemetry configuration example
  docs/guidelines/repository-guidelines/01-new-repository-settings.md
Labels: size/XS, lgtm, cla: yes
