Repository kyma-project/community, pull requests merged in 2024-10, with the labels that each got.

#942 fix dead link to kyma-cr.md
  concepts/central-resource-sync/README.md
Labels: size/XS, lgtm, cla: yes

#943 Clean up obsolete release guidelines
  docs/guidelines/releases-guidelines/01-release-strategy.md
  docs/guidelines/releases-guidelines/02-kyma-release-process.md
  docs/guidelines/releases-guidelines/03-kyma-cli-release-process.md
  docs/guidelines/releases-guidelines/05-release-communication.md
  docs/guidelines/releases-guidelines/06-release-process-improvement.md
  docs/guidelines/releases-guidelines/07-release-subscription.md
  docs/guidelines/releases-guidelines/README.md
  docs/guidelines/releases-guidelines/assets/release-PR.png
  docs/guidelines/releases-guidelines/metadata.yaml
Labels: area/documentation, size/L, lgtm, cla: yes

#944 Update repository guidelines and style and terminology
  docs/guidelines/content-guidelines/02-style-and-terminology.md
  docs/guidelines/repository-guidelines/01-new-repository-settings.md
  docs/guidelines/repository-guidelines/02-repository-template.md
Labels: size/S, lgtm, cla: yes

#947 Update broken links
  concepts/central-resource-sync/README.md
Labels: size/XS, lgtm, cla: yes

#949 Fix dead link for the Image Syncer
  docs/guidelines/technical-guidelines/02-docker-images.md
Labels: size/XS, lgtm, cla: yes
