Repository kyma-project/community, pull requests merged in 2024-02, with the labels that each got.

#884 Fix a link
  concepts/observability-strategy/configurable-logging/03-fluent-bit-operator1.md
Labels: area/documentation, size/XS, lgtm, cla: yes

#886 Update the note in the Panels section
  docs/guidelines/content-guidelines/03-formatting.md
Labels: size/XS, lgtm, cla: yes

#887 Add tj-actions/changed-files to allowed actions
  docs/contributing/assets/allowed_actions.json
Labels: size/S, lgtm, cla: yes

#892 Disable link checker for the Stack Overflow page
  docs/README.md
Labels: size/XS, lgtm, cla: yes

#893 Add Jan and Till to Emeritus File
  emeritus.md
Labels: size/XS, lgtm, cla: yes

#894 Disable link checker for the Stack Overflow page
  README.md
Labels: size/XS, lgtm, cla: yes

#890 adds golangci/golangci-lint-action@v4 to the allowed actions
  docs/contributing/assets/allowed_actions.json
Labels: size/S, lgtm, cla: yes
