Repository kyma-project/community, pull requests merged in 2024-09, with the labels that each got.

#928 Add guidelines for AI-generated code contributions
  docs/contributing/02-contributing.md
Labels: size/S, lgtm, cla: yes

#927 Update allowed GitHub Actions versions
  docs/contributing/assets/allowed_actions.json
Labels: size/XS, lgtm, cla: yes

#929 Add allcheckspassed to allowed_actions.json
  docs/contributing/assets/allowed_actions.json
Labels: size/S, lgtm, cla: yes

#931 Remove an obsolete link
  sigs-and-wgs/archive/wg-showcase-application/README.md
Labels: area/documentation, size/XS, lgtm, kind/chore, cla: yes

#932 Update Content Strategy
  docs/guidelines/content-guidelines/00-content-strategy.md
  docs/guidelines/content-guidelines/07-release-notes.md
  templates/resources/release-notes-input.md
  templates/resources/release-notes.md
  templates/resources/task.md
Labels: area/documentation, size/L, lgtm, cla: yes

#934 expand guidelines README
  docs/guidelines/content-guidelines/README.md
  docs/guidelines/templates/templates-type.md
Labels: size/M, lgtm, cla: yes

#935 Add reuse
  .reuse/dep5
Labels: size/S, lgtm, kind/chore, cla: yes

#940 Remove inappropriate versions from allowed actions list
  docs/contributing/assets/allowed_actions.json
Labels: size/S, lgtm, cla: yes
