Repository kyma-project/community, pull requests merged in 2024-03, with the labels that each got.

#896 Replace a link to Span Metrics Processor README
  concepts/observability-strategy/configurable-monitoring/pocs/shared-vs-per-sinal-type-collector/README.md
Labels: size/XS, lgtm, cla: yes

#897 Fix the link to Kyma Slack channels
  README.md
  docs/README.md
  docs/guidelines/releases-guidelines/05-release-communication.md
Labels: area/documentation, size/XS, lgtm, kind/chore, cla: yes

#900 Unordered lists are appropriate for items that have no sequential order
  sigs-and-wgs/archive/sig-core/proposals/central-connector-service.md
Labels: size/S, lgtm, cla: yes

#901 updated eventing code guidelines
  concepts/eventing-code-guidelines.md
Labels: size/S, lgtm, cla: yes

#902 Add gitleaks/gitleaks-action action to allowed actions
  docs/contributing/assets/allowed_actions.json
Labels: size/S, lgtm, cla: yes

#903 Switch to md-check-link
  .github/workflows/lint-markdown-links-daily.yml
  .github/workflows/lint-markdown-links-pr.yml
  .github/workflows/pr-docu-checks.yml
Labels: area/documentation, size/M, lgtm, cla: yes

#904 Apply markdowlint rules in the community repository
  docs/contributing/02-contributing.md
  docs/contributing/03-git-workflow.md
  docs/contributing/04-sig-and-wg.md
  docs/governance/01-governance.md
  docs/governance/02-steering-committee.md
  docs/governance/03-issues-workflow.md
  docs/guidelines/content-guidelines/02-style-and-terminology.md
  docs/guidelines/content-guidelines/03-formatting.md
  docs/guidelines/content-guidelines/04-ui-elements.md
  docs/guidelines/content-guidelines/05-tabs-toggles.md
  docs/guidelines/content-guidelines/06-links.md
  docs/guidelines/content-guidelines/07-release-notes.md
  docs/guidelines/content-guidelines/09-diagrams.md
  docs/guidelines/content-guidelines/10-docs-preview.md
  docs/guidelines/releases-guidelines/02-kyma-release-process.md
  docs/guidelines/releases-guidelines/03-kyma-cli-release-process.md
  docs/guidelines/repository-guidelines/01-new-repository-settings.md
  docs/guidelines/technical-guidelines/04-http-api-design.md
  docs/guidelines/technical-guidelines/05-test-strategy.md
  heading_capitalization.js
Labels: size/L, lgtm, cla: yes

#905 Fix section links
  concepts/central-resource-sync/README.md
Labels: size/S, lgtm, cla: yes

#906 Removed outdated mlc config
  .mlc.config.json
  concepts/modularization/README.md
Labels: area/documentation, size/S, lgtm, cla: yes

#907 Usage of md-link-check reflected in repository guidelines
  docs/guidelines/repository-guidelines/01-new-repository-settings.md
Labels: area/documentation, size/M, lgtm, cla: yes
