Repository kyma-project/community, pull requests merged in 2024-01, with the labels that each got.

#876 Adjust docs to new guidelines
  docs/contributing/01-code-of-conduct.md
  docs/contributing/02-contributing.md
  docs/contributing/03-git-workflow.md
  docs/contributing/04-sig-and-wg.md
  docs/contributing/05-gh-actions.md
  docs/contributing/README.md
  docs/governance/01-governance.md
  docs/governance/02-steering-committee.md
  docs/governance/03-issues-workflow.md
  docs/governance/README.md
  docs/guidelines/README.md
  docs/guidelines/content-guidelines/03-formatting.md
  docs/guidelines/content-guidelines/05-tabs-toggles.md
  docs/guidelines/content-guidelines/09-diagrams.md
  docs/guidelines/releases-guidelines/01-release-strategy.md
  docs/guidelines/releases-guidelines/02-kyma-release-process.md
  docs/guidelines/releases-guidelines/03-kyma-cli-release-process.md
  docs/guidelines/releases-guidelines/05-release-communication.md
  docs/guidelines/releases-guidelines/06-release-process-improvement.md
  docs/guidelines/releases-guidelines/07-release-subscription.md
  docs/guidelines/releases-guidelines/README.md
  docs/guidelines/repository-guidelines/01-new-repository-settings.md
  docs/guidelines/repository-guidelines/02-repository-template.md
  docs/guidelines/repository-guidelines/README.md
  docs/guidelines/technical-guidelines/01-naming.md
  docs/guidelines/technical-guidelines/02-docker-images.md
  docs/guidelines/technical-guidelines/03-helm.md
  docs/guidelines/technical-guidelines/04-http-api-design.md
  docs/guidelines/technical-guidelines/05-test-strategy.md
  docs/guidelines/technical-guidelines/README.md
  docs/guidelines/templates/README.md
  docs/guidelines/templates/templates-type.md
  docs/kyma-release-notes/2023-08-31-release-notes-2.18.md
  templates/resources/architecture.md
  templates/resources/configuration.md
  templates/resources/custom-resource.md
  templates/resources/release-notes-input.md
  templates/resources/release-notes.md
  templates/resources/sig-wg-readme-template.md
Labels: area/documentation, size/L, lgtm, kind/chore, cla: yes

#878 Fix a broken link
  docs/guidelines/repository-guidelines/01-new-repository-settings.md
Labels: area/documentation, size/XS, lgtm, kind/chore, cla: yes

#879 Update section links
  docs/contributing/05-gh-actions.md
  docs/governance/01-governance.md
  docs/governance/03-issues-workflow.md
  docs/guidelines/content-guidelines/01-user-docs.md
  docs/guidelines/content-guidelines/02-style-and-terminology.md
  docs/guidelines/repository-guidelines/README.md
Labels: size/S, lgtm, cla: yes

#880 Disable the link check for a section
  docs/guidelines/content-guidelines/01-user-docs.md
  docs/kyma-release-notes/2023-08-31-release-notes-2.18.md
Labels: size/XS, lgtm, cla: yes

#881 Link check disable
  docs/guidelines/content-guidelines/01-user-docs.md
Labels: size/XS, lgtm, cla: yes

#882 Disable the check
  docs/guidelines/content-guidelines/01-user-docs.md
Labels: size/XS, lgtm, cla: yes

#883 Fix broken links
  concepts/admission-webhook-cert-management/README.md
  concepts/installer-migration-hooks/README.md
  docs/governance/02-steering-committee.md
  sigs-and-wgs/archive/sig-core/README.md
  sigs-and-wgs/archive/sig-core/proposals/extending-kyma-cli.md
  templates/resources/configuration.md
  templates/resources/release-notes.md
Labels: size/S, lgtm, cla: yes
